### ISSUE TITLE
Major rename

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1244]
## Goal:

```javascript
@Component({
  // Public API
  selector: 'selector',
  properties: [],
  events: [],

  // View
  viewActions: []

  // HostElement
  hostSetters: {},
  hostListeners: {},
  hostActions: {},
  hostAttributes: {},
})
```

## Existing Classes

* [x] `View` => `RenderView` /  `AppView`
* [x] `ProtoView` => `RenderProtoView` / `AppProtoView`
* [ ] INTERNAL API: `ChangeDetector` => `Detector`
* [x] ~~PUNTING: `Directive` (annotation) => `AbstractDirective`~~ 
* [x] `Template` => `View`
* [x] ~~PUNTING: `Viewport` => `Template` (Because now Template is free)~~
* [ ] Have `Component` extend `Decorator`
* [ ] `Decorator` => `Directive`

NOTE: `Render` prefix for Render and `App` for App

## Class `Component` property renames

* [x] `services` => `injectables` see #973
* [x] `bind` => `properties` (change from map to just a list)
* [x] `events` (create implement later, replacement for `@EventEmitter`) #1376
* [ ] `viewActions` (create implement later) #1251
* [x] `events` => `hostListeners` (map)
* [x] no concept => `hostSetters` (map, declare, implement later) #1256
* [ ] no concept => `hostActions` (map, declare, implement later) #1251
* [ ] no concept => `hostAttributes` (map, declare, implement later) #1402

## Class `Template` => `View` property renames

* [x] `inline` => `template`
* [x] `url` => `templateUrl`
* [ ] introduce `stylesheets` (implement later)
* [ ] introduce `stylesheetUrls` (implement later)

## Emitter

* [ ] Angular should autodetect the emitter type. That is it could be `Rx.Subject` or `dart.Stream`

## Example:

```javascript
// Component annotation
// <prompt question="What is your name?" (answer)="greet($event)"></prompt>
@Component({
  // PUBLIC BINDINGS
  selector: 'prompt',
  properties: ['question'],
  events: ['answer'],

  // VIEW PRIVATE
  commands: ['focus'],
  listen: { 'click': 'ask()' }
})
// View Annotation
@View({
  template: `
    <form (submit)="onAnswer(input.value)" [hidden]="!show">
      {{question}}
      <input #input @focus="input.focus()">
    </form>
  `,
  stylesheets: [],
  directives: []
})
// Component Controller
class Prompt {
  // PUBLIC BINDINGS
  question:string;
  answer:Emitter;

  // VIEW PRIVATE
  show:bool;
  focus:Emitter;

  constructor() {
    this.focus = new Emitter();
    this.success = new Emitter();
  }

  ask() {
    this.show = true;
    this.focus.call();
  }
  
  onAnswer(value) {
    this.answer.call(value);
    this.show = false;
  }
}
```

**Comment by PascalPrecht** [comment]
@mhevery woudl `stylesheets` in `View` annotations load stylesheets, as in files that will be embedded? Or is that annotation property just for inline styles.

**Comment by gjungb** [comment]
@mhevery the example seems to be inconsistent, because you propose to rename the property ```events``` to ```listen```, while in the example you use ```listeners```.

**Comment by otodockal** [comment]
Maybe it should be better to rename "inlineTemplate" to "template". It's shorter.

**Comment by mhevery** [comment]
Updated per your comments

**Comment by gjungb** [comment]
I was just wondering whether the following would make sense: "as the author of the ```Prompt``` component I expect that":
1.  ```question``` is a string.
2.  Angular will warn me / throw if ```question``` is not a string

Given this, I would rewrite the ```properties``` field to something like:
> properties: {
> "question": "string"
> }

**Comment by mhevery** [comment]
@gjungb I don't think angular should be in the business of enforcing types. I think we should leave type validation to TypeScript.

**Comment by gjungb** [comment]
@mhevery o.k. makes sense. BTW: I really like the switch from object to array / list, because I never got the clue why one would have different names for attributes / properties vs. local / scope variables.

**Comment by ladyborg** [comment]
So I noticed that `stylesheets` and `stylesheetUrls` are plural while `template` and `templateUrl` are not.

Are we going to be able to define an array of style sheets to apply to a component? I think that's a great idea, but what about if you wanted to be able to define an array of templates for a single component and use those templates conditionally or construct a template from various smaller template chunks in an array of template chunks? I'm sure some people would think that this is a waste because you can just make multiple components and then compose with components, but what if you didn't want to create an entire component just to use it as a piece of DOM?

Either way, I thank my stars for \`multi-line strings\` in es6 so I don't have to use JSX lol

**Comment by mhevery** [comment]
@ladyborg i think your use case will be covered with allowing multiples `@View`s per compenent. Not speced out yet.

**Comment by ladyborg** [comment]
Ahhhh, I like that better actually. It could allow for better encapsulation and better testing.

**Comment by SekibOmazic** [comment]
@mhevery So references are `#`-prefixed (already so) and commands are `@`-prefixed? (in markup)

And is `$` in `@focus="$input.focus()"` and `(submit)="onAnswer($input.value)"` a typo?

**Comment by mhevery** [comment]
@SekibOmazic fixed the typo

**Comment by IgorMinar** [comment]
1. `ChangeDetector` -> `Detector` - seems too abiguous
2. `Viewport` -> `Template` - so now we'll have component directives which have views that have templates, but also template directives that have no views and hence no templates? that seems confusing

**Comment by naomiblack** [comment]
@jelbourn can you file some issues for the outstanding issues and put them in M9 as appropriate, then close?

**Comment by jelbourn** [comment]
Tracking remaining work via:
#1582 (stylesheets and stylesheetUrls)
#1251 (actions)
#1536 (Viewport and Decorator)
