### ISSUE TITLE
Create actions concept (View & Host)

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1251]
Actions are a way to decouple invoking of methods on the `View` /` `Host` element from the Component Controller.

### Tasks

- [x] create `Component.hostActions:List<string>'
- [ ] create `Component.viewActions:Map<string, string>'
- [ ] ~~update `Parser` to understand qualifier syntax: `qualifier: statement`~~
- [ ] support `@action="if ($element==$self) $self.focus()"` #2022
- [ ] update `Compiler` to understand `@action="statement"` syntax
- [ ] create glue code (Maybe `ChangeDetector`) which will route actions between controller and the `View` / `Host` element.

### Goals:

* Different templates may have different ways of invoking behavior. For example the `<video>` tag on mobile may have `play()` method where as desktop template may have a `start()` method.
* By invoking do commands we can marshal the events across UI/WebWorker boundries.
* We assume that all subexpressions which start with `$` must be avaluated on the UI thread and everything else is evaluated on the WebWorker thread.

## API

Commands are `Emitter`s which are listed in the `@Component.events` Declaration. (See #1250)

```javascript
@Component({
  selector: 'my-component',
  viewActions: ['play'],
  hostActions: {
    'visible': '$element.scrollIntoView()'
  }
})
@View({
  template: `<video @play="$element.play()" [src]="videoUrl"></video>`
}) 
class {
  play:Emitter;
  visible:Emitter;

  constructor() {
    this.play = new Emitter();
    this.visible = new Emitter();
  }

  playVideo() {
    this.play.emit();
    this.visible.emit();
  }
}
```

## ~~Qualifiers~~

Dropping in favor of #2022 (`if-else`)

By default the emitter does not take an argument and all `@name="statement"` will fire. Optimally the emitter's `emit()` method may take an optional qualifier argument. In such as case only the conman which has the identical (`===`) qualifier will fire. `@name="qualifier: statement"`.

## More complex example

```javascript
@Copmonent({
  selector: 'my-component',
  actions: ['focus', 'play', 'select']
})
@View({
  platform: 'mobile', // not implementd yet
  template: 'my_component.mobile.html'
})
@Template({
  platform: 'desktop', // not implemented yet
  url: 'my_component.desktop.html'
})
class MyComponent {
  items:Array;
  strength:string;
  
  focus:Emitter;
  play:Emitter;
  select:Emitter;

  constructor(view:View) {
    items = [{name:'a'}, {name:'b'}];
    
    focus = new Emitter();
    play = new Emitter();
    select = new Emitter();
  }
  
  doSomething() {
    focus.emit('username'); // use qualifier
    play.emit(); // no qualifier
    select.emit(items[1]); // qualifier used with for directive
    select.emit('select', 'item2')
  }
}
```

`my_component.desktop.html`:
```
<div>
  <input name="username" @focus="'username': $self.focus()">
  <input name="password" @focus="'password': $self.focus()">
  <input [control]="item" @focus="item: $self.focus()" @blur="item: $self.blur()">
</div>
<ul>
  <li *for="item in items" @select="item: $self.select(strength)">{{item.name}}</li>
  <li #item-{{$index}}  *for="item in items | random" @select="item: $self.select(strength)">{{item.name}}</li>
</ul>
<button (click)="$self.ripple($event)"></button>

<video @play="$self.play()">
```

`my_component.mobile.html`:
```
<media src="..." @play="$self.start()">
```

## Action Syntax

```html
<div @action="qualifier: statement">
<div do-action="qualifier: statement">
```

### Action Syntax Considered

```html
<div (*action)="qualifier: statement">
<div )action(="qualifier: statement">
<div {action}="qualifier: statement">
<div &action="qualifier: statement">
<div !action="qualifier: statement">
```

**Comment by PascalPrecht** [comment]
In #1250 emitters are declared on `Component.events`, is this just not in sync with this issue where `Component.commands` are used, or are these two different things then?

**Comment by PascalPrecht** [comment]
Ah just saw #1244

**Comment by Baudin999** [comment]
If you are considering Commands, might it not also be a good idea to think about chaining them? Piping the result from the first command into the second command and awaiting asynchronous results before continuing.

The syntax could be something along the lines of:

```actions: ['select::validate::play', 'focus']```

Adding actions (or commands) to views would be great as well:

```
@View({
  platform: 'mobile', // not implementd yet
  template: 'my_component.mobile.html',
  actions: ['onLoad::selectFirstElement', 'onDispose::disposeActiveRecord']
})
```

**Comment by matanlurey** [comment]
Maybe I missed this above, but how do I fire an action (e.g. focus) on an element several levels deep (e.g. nested within a component within a component), or what would be the recommended pattern to get through this?

**Comment by vsavkin** [comment]
After a few discussions, we have decided to extend the Query mechanism first to see if it is sufficient to cover all the use cases, and if we need to implement actions at all. Closing this issue for now.

https://github.com/angular/angular/issues/2482
