### ISSUE TITLE
aio: Things to improve for aio PR previews

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#14922]
The initial implementation is in #14330. This is a list of things that need to be fixed/improved (more to be added as we test this functionality in practice):

- [x] Disable HTTP (possibly redirect to HTTPS). (#14922)
- [x] Do not fail the `aio` job for PRs that are not allowed to upload (based on the current policy). (#14330)
- [x] Do not fail the `aio` job when uploading the same build artifacts for the same SHA (e.g. when rerunning a previously successful job). (#15940)
- [x] Add rotation for logs. (#15984)
- [x] Keep the logs on the host machine instead of the docker container. (#14922)
- [ ] Make the upload functionality more reusable (e.g. move the relevant bits from `aio/scripts/deploy-preview.sh` to `aio/aio-builds-setup/scripts/upload.sh` and make it accept the input directory and target domain as inputs).
- [x] Standardize the process of updating the docker image on the VM (and make it reusable for different projects). (#16844)
- [x] Add more docs (e.g. about how it works, how to set it up on a VM, how to configure, etc). (#14922)
- [ ] Add more e2e tests to cover:
    - [ ] Verifying uploads (JWT verification, PR author retrieval, Team membership check).
    - [ ] Posting preview links as PR comments. 
- [ ] Use the "next page" links [returned as headers][1] from GitHub API for retrieving lists of things (e.g. PRs). 
- [ ] Set up VM/app monitoring?

[1]: https://developer.github.com/v3/issues/#list-issues

**Comment by petebacondarwin** [comment]
* [ ] deeplinks into the app return 404 - we need to rewrite these to the index.html

**Comment by petebacondarwin** [comment]
@gkalpak are the unticked items in this issue still relevant?

**Comment by gkalpak** [comment]
They are nice-to-haves but not necessary. Feel free to close.
