### ISSUE TITLE
aio milestones

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#15259]
Milestones:
- [x] doc-v2.angular.io - Igor/Ward
- [ ] header/footer/all marketing pages look good - Ward/Jules/Stef
- [x] plunkers and zip archives work - Pete/Jesus
- [x] view and interact with examples and code snippets - Pete/Ward
- [x] guide styles look good - Stef
- [ ] api styles look good - Stef/Pete/Ward
- [x] transition content authoring to angular/angular - Ward/Pete

**Comment by petebacondarwin** [comment]
We need owners for these milestones, since some of them need specific people to work on them.
E.g. 

 doc-v2.angular.io -> Igor
 header/footer/all marketing pages look good -> Jules/Stefanie?
 plunkers and zip archives work -> Jesus
 view and interact with examples and code snippets -> Pete

etc.

**Comment by wardbell** [comment]
I added owners

**Comment by petebacondarwin** [comment]
The marketing milestone is being tracked via #16228 
The API styling is tracked in #16210
