### ISSUE TITLE
Router tutorial tour of heroes lacks milestone stackblitz/executable/downloads

### ISSUE THREAD

**Issue by jgfet** [angular/angular#17794]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The link you download is a zip file. With a setup that probably relates to the 'end game'.
If you want to download and run and gradually add code, nothing jives.
Furthermore, it's not a CLI project, which adds to the confusion. See my comment here:
https://stackoverflow.com/questions/44779294/

Additionally for milestone 3 wrap up
https://angular.io/guide/router#milestone-3-wrap-up
you haven't even included 
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
in app-module.ts in tabbed sources 
or in imports: [   ...BrowserAnimationsModule] 
Folder structure + tabbed sources makes no reference to animations.ts 

By milestone 5 
https://angular.io/guide/router#component-less-route-grouping-routes-without-a-component
I'd completely lost the plot...
None of source in download syncs to anything. app-modules.ts

zipped download has these extra imports:
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { Router } from '@angular/router';
import { ComposeMessageComponent } from './compose-message.component';
import { LoginRoutingModule }      from './login-routing.module';
import { LoginComponent }          from './login.component';

website makes reference to:
import { AdminModule }             from './admin/admin.module';
That's never used in zipped download.

Later in Milestone 6
https://angular.io/guide/router#preloading-background-loading-of-feature-areas
app-module.ts more closely resembles zip. But AdminModule is no more...
..
I actually had to do a top down search of the web page for 'AdminModule' to realise that it had been lazy loaded via. This more than anything makes the case for needing versions you can check out of git. and be able to diff them..
loadChildren: 'app/admin/admin.module#AdminModule'
I'd missed the vital bit of info here on a first read thru:
https://angular.io/guide/router#lazy-loading-route-configuration

Additionally - not sure if this was a deliberate mistake.. but setting of session id only ever appears in url if you've gone to admin page before attempting to login...

## Expected behavior

You have several points throughout the code that you can pull the code from a git repo, so you can manually add the code from the appropriate starting point and be able to follow along and better cement an understanding by 'doing' rather than 'reading'

For milestone 3:
corrected app.modules.ts in tabs and also add animations.ts to tab & source folders.

## Minimal reproduction of the problem with instructions

Just try downloading the zip and find this in app.module.ts.
import { RouterModule, Routes } from '@angular/router';

## What is the motivation / use case for changing the behavior?

Make it so I can code along and better understand, rather than dry reading exercise.

## Please tell us about your environment
@angular/cli: 1.1.3
    node: 8.1.2
    os: darwin x64
    @angular/animations: 4.2.4
    @angular/common: 4.2.4
    @angular/compiler: 4.2.4
    @angular/compiler-cli: 4.2.4
    @angular/core: 4.2.4
    @angular/forms: 4.2.4
    @angular/http: 4.2.4
    @angular/platform-browser: 4.2.4
    @angular/platform-browser-dynamic: 4.2.4
    @angular/platform-server: 4.2.4
    @angular/router: 4.2.4
    @angular/tsc-wrapped: 4.2.4
    @angular/upgrade: 4.2.4
    @angular/cli: 1.1.3
<pre><code>
Angular version: X.Y.Z

@angular/cli: 1.1.3
node: 8.1.2
os: darwin x64

Browser:
- [ x] Chrome (desktop) version Version 59.0.3071.115  Mac OS X Sierra 10.12.5
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform: Mac

Others:

</code></pre>

**Comment by atscott** [comment]
Copying issue description from #27871 (marking as duplicate of this one)

### Description

 
The guides do not have a result zip for each milestone/step, which would be ideal to check if your local code conforms to what this would be

This improvement would be ideal as well, for anyone who would like to start from any milestone without having to start all over from scratch

In my case, I'm following the [Routing & Navigation Guide](https://angular.io/guide/router) and some changes that I made, causes the application not to have the behavior expected. Since I am learning, I do not know in which milestone I diverged nor in which part of the code. I only have access to the final version, where the project structure is already very different from the milestone I am (Milestone 4: Crisis center feature)

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
