### ISSUE TITLE
List of updates needed for CLI docs

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#19510]
The documentation team is revising the docs to show usage of the Angular CLI.

Details about the work to be done for each guide are [here](https://docs.google.com/document/d/1lqkZV_cIznrZfuP22VolSpRlrhbwmyOb3T_bxcsImjQ/edit)

This issue  tracks progress on that plan.

- [x] AJS quick reference (#19552)
- [x] Animations (#19551)
- [x] AOT - Recommend: delete after moving overview to "Metadata and AOT" which we rename "AOT". #19818
- [x] Attribute Directives - This step-by-step guide needs new steps. #19771
- [x] Bootstrapping - update w/ code from CLI. Add sentence about `providers`. #19777
- [x] Browser Support - a few sentences. #19843
- [x] Component Styles - fix what is no longer true under CLI #19791
- [x] Dependency Injection - describe how the CLI does (or does not register). #19892
- [x] Deployment - Needs work. Replace many SystemJS specifics with WebPack/CLI specifics. #19839
- [x] Displaying Data (#19574)
- [x] Glossary - remove SystemJs entries and Setup references. Define "CLI".
- [x] i18n - Needs work.This step-by-step guide needs new steps. Code must change too because that is different under CLI. @ocombe is leading this one.
- [x] ngModule - Per Kapunahele, we should update for CLI _without regard_ for her pending changes as they will not arrive in time. She will reconcile later. #19776
- [x] NPM packages - rewrite to reflect `package.json` from the CLI. #19850
- [x] Pipes (#19553)
- [x] Reactive Forms - This step-by-step guide needs new steps. Needs attention to adding of bootstrap style.
- [ ] Router - This step-by-step guide needs new steps. Port changes. Folder structure. Brandon is working on this. #20023
- [x] Template-driven Forms - This step-by-step guide needs new steps. Needs attention to adding of bootstrap style.
- [x] Testing - Needs work. Commands change. Terminal output from CLI is different. Must describe where the Karma.config comes from. Remove SystemJS refs. Re-describe `compileComponent` in light of WebPack effects. A few hours of work required. #20697
- [x] Tour of Heroes - incorporate Jules' work first. #19811
- [ ] Typescript configuration - Many differences from CLI to be removed. Not a big deal. 
WB: This guide is wildly at odds with the three files emitted by the CLI and even when the guide is correct, it doesn't add much value. The CLI itself should document the three `typescript.config` files. Recommend deleting this guide.
- [x] Universal - adjust guide, after it is merged in present form, to replaces SystemJS aspects with CLI aspects. 
- [ ] VS 2015 QS - Recommend we drop as outdated.  Today we'd recommend a different path for .NET 4.6 apps and probably recommend VS 2017 with .NET Core for new apps. This is a sink hole.
- [x] Sweep selectors and change "my-app" to "app-root". #19778

We think all of this should be doable in <30 hours with the exception of Tour of Heroes which is really a separate topic.

**Comment by jbogarthyde** [comment]
Looks done - closing it. Please re-open or create new issue if you find something that hasn't been done.
