### ISSUE TITLE
AIO: Add developer survey link to top of pages

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#21094]
## I'm submitting a...
<pre><code>
[X] Feature request
</code></pre>

## Expected behavior
At the top of every page there should be a link to complete the developer survey (LINK TBD). Users should be able to dismiss this top bar and not see it again.

**Comment by IgorMinar** [comment]
## Work breakdown

- [ ] UX spec for the homepage
- [ ] UX spec for other marketing pages (/news, /resources, ..)
- [ ] UX spec for doc pages (/docs, /docs/*)
- [ ] Content spec
  - [ ] Text and link
  - [ ] Campaign duration
- [ ] Implementation

**Comment by sjtrimble** [comment]
![aio-surveydesign_desktop-final](https://user-images.githubusercontent.com/2958442/34178941-d281d0b8-e4bd-11e7-874b-3b4cedad4b21.png)
![aio-surveydesign_staticbar-mobile copy](https://user-images.githubusercontent.com/2958442/34178942-d2994946-e4bd-11e7-92cd-ec902f95b578.png)

- Icons used: "insert_comment" and "close"
- Gray background: $darkgray (#333333)
- Red button: $brightred (#dd0031)
- Font-size: 16px
- Ideal toolbar height: 56px (can be 60px if needed)
- Maintain 16px margin/padding left and right
- Content centered vertically in bar

**Comment by IgorMinar** [comment]
> Content centered vertically in bar
 
Only for desktop? For mobile it seems to be left aligned on the mock image.

Also on mobile, it's not clear that the text is a link. Could we add some visual cue to let the user know how to go to the survey? (maybe underline part of the text?)

> Message appears per session

That sounds like a really bad user experience. Most sessions on angular.io are short-lived, which means that the users will have to close the notification several times during the campaign.

I suggest we do not show the same notification again if the user closes it once.

> Message bar appears after a few seconds (3)

What do you mean by this? If I navigate to angular.io on desktop I should see nothing and after 3 seconds the notification bar appears and pushes down the normal content? Or do you mean something else?

> "Let us know what you think by taking a quick survey!"

Can I also request that the notification text is more descriptive? Right now it's not clear if the survey is about angular.io, Angular or something else. How about: "Let us know what you think about Angular by taking a quick survey!". Hopefully we can fit this into the mobile version.

@StephenFluin Lastly, we should build this so that the campaign auto-expires after a set date. Otherwise we might be displaying the banner days after the survey is closed if for whatever reason we can't push an update to the site (or the site is snapshotted for archival purposes like v4.angular.io while a campaign is active). We can always end a campaign early if needed.

**Comment by sjtrimble** [comment]
> **Content centered vertically in bar**

>> Only for desktop? For mobile it seems to be left aligned on the mock image.

I recommend having both center aligned. I can update the mobile mockup to reflect that.

>> Also on mobile, it's not clear that the text is a link. Could we add some visual cue to let the user know how to go to the survey? (maybe underline part of the text?)

Underline is not visually appealing (I tried that). We could 1) bold the text "quick survey", 2) change the text on mobile to say "Click to ..." or 3) change the text to a shortened version such as "Tell us about your experience with Angular (assuming the modified text below)." with a button next to it that reads "Take Survey". I think the first is the easiest but open to feedback/preferences. 

> **Message appears per session**

>> That sounds like a really bad user experience. Most sessions on angular.io are short-lived, which means that the users will have to close the notification several times during the campaign.

>> I suggest we do not show the same notification again if the user closes it once.

If the user has already taken the survey, it would be certainly good to not show the message per session. For all others, I don't see an issue with reminding them more than once. Your approach works - but I'd recommend you post it elsewhere so that a user can get to it elsewhere perhaps? The though process behind this is that perhaps a user just clicks away the message without reading it or really paying attention to it the first time, but may be willing to take the survey at a later point in time, perhaps when the user is not in a rush to get the information they need. I leave it up to you guys to decide what is best.

> Message bar appears after a few seconds (3)

>> What do you mean by this? If I navigate to angular.io on desktop I should see nothing and after 3 seconds the notification bar appears and pushes down the normal content? Or do you mean something else?

Response

> "Let us know what you think by taking a quick survey!"

>> Can I also request that the notification text is more descriptive? Right now it's not clear if the survey is about angular.io, Angular or something else. How about: "Let us know what you think about Angular by taking a quick survey!". Hopefully we can fit this into the mobile version.

What about "Tell us about your experience with Angular by taking a quick survey!" @StephenFluin may need to provide additional input here based on survey goals / messaging.

Initially the thought process was to keep it simple - those that are interested in providing feedback will click regardless of how descriptive the text is. Additionally, the survey is only 3 questions long and a user can easily and quickly decide whether they want to participate or not. I do recommend keeping it very very simple, as most users are less likely read a long sentence.

______________

Let me know if I missed anything!

**Comment by IgorMinar** [comment]
**Content centered vertically in bar**
>>> Only for desktop? For mobile it seems to be left aligned on the mock image.
> I recommend having both center aligned. I can update the mobile mockup to reflect that.

yup. I see you updated it already. thanks!

>> Also on mobile, it's not clear that the text is a link. Could we add some visual cue to let the user know how to go to the survey? (maybe underline part of the text?)

> Underline is not visually appealing (I tried that). We could 1) bold the text "quick survey", 2) change the text on mobile to say "Click to ..." or 3) change the text to a shortened version such as "Tell us about your experience with Angular (assuming the modified text below)." with a button next to it that reads "Take Survey". I think the first is the easiest but open to feedback/preferences. 

bold looks good. I see you updated the mock. thanks!

**Message appears per session**

>> That sounds like a really bad user experience. Most sessions on angular.io are short-lived, which means that the users will have to close the notification several times during the campaign.
>> I suggest we do not show the same notification again if the user closes it once.

>If the user has already taken the survey, it would be certainly good to not show the message per session. For all others, I don't see an issue with reminding them more than once. Your approach works - but I'd recommend you post it elsewhere so that a user can get to it elsewhere perhaps? The though process behind this is that perhaps a user just clicks away the message without reading it or really paying attention to it the first time, but may be willing to take the survey at a later point in time, perhaps when the user is not in a rush to get the information they need. I leave it up to you guys to decide what is best.

Since we don't have a way to know if someone took a survey or not we can't stop displaying the notification based on that.

Most of the session on angular.io are short lived - people come, look up an api doc and leave. If we show them the notification every time they come that will be really annoying. 

I see three options:

1. dismissal is persisted across sessions - keep on displaying until the user clicks the "dismiss" (x) button and then do not display any more for the current campaign
2. dismissal is not persisted across sessions - display every time during the campaign duration
3. persist dismissal after N-th dismissal - this is really a combination of 1 and 2

I think that 1. is the most sensible, we want to expose the survey to more people and not to bombard them with it. This is also how the github campaign notification bar works (e.g. for net neutrality), so that's a good guiding precedence for us. @StephenFluin do you agree?

**Message bar appears after a few seconds (3)**

>> What do you mean by this? If I navigate to angular.io on desktop I should see nothing and after 3 seconds the notification bar appears and pushes down the normal content? Or do you mean something else?

> This was a request from the team - I don't think it adds too much value, so it's up to you guys. The intent was that the notification bar "drops down" 3 seconds after the page has finished loading (and pushed down the normal content, as you said), or within 3 seconds in general.

Imaging this experience gives me flashbacks of all the poorly designed news sites that lazy load and aggressively display ads via delayed overlays. 

I think we should again take github's net neutrality banner as an guiding example and just render the banner during the initial rendering without any kind of delays.

**"Let us know what you think by taking a quick survey!"**

>> Can I also request that the notification text is more descriptive? Right now it's not clear if the survey is about angular.io, Angular or something else. How about: "Let us know what you think about Angular by taking a quick survey!". Hopefully we can fit this into the mobile version.

> What about "Tell us about your experience with Angular by taking a quick survey!" @StephenFluin may need to provide additional input here based on survey goals / messaging.

> Initially the thought process was to keep it simple - those that are interested in providing feedback will click regardless of how descriptive the text is. Additionally, the survey is only 3 questions long and a user can easily and quickly decide whether they want to participate or not. I do recommend keeping it very very simple, as most users are less likely read a long sentence.

how about: 
- `before:  ` "Let us know what you think by taking a **quick survey**!"
- `after 1:  ` "Help Angular by answering these **4 survey questions**!"
- `after 2:  ` "Help Angular by answering **these 4 questions**!"
- `after 3:  ` "Help Angular by taking a **1 minute survey**!

@StephenFluin do you have a preference?

**Comment by StephenFluin** [comment]
My hope was to save the first dismissal whenever possible (cookie / session / localStorage), so I agree with 1.

If waiting to drop down doesn't add value, then cut it and render on initial load, sounds good.

After #3 would be my preference.

**Comment by IgorMinar** [comment]
OK. I'll summarize the spec in a bit.

**Comment by IgorMinar** [comment]
The final spec is:

- Icons used: "insert_comment" and "close"
- Gray background: $darkgray (#333333)
- Red button: $brightred (#dd0031)
- Font-size: 16px (14px on mobile)
- Ideal toolbar height: 56px (can be 60px if needed)
- Maintain 16px margin/padding left and right
- Content centered vertically & horizontally in bar (except close button and margins required)

Desktop & Mobile:
- Click on "message" icon or text to navigate to survey
- Remove message bar by clicking on "x" close icon (slide up would be nice animation)
- The message appears on each rendering of the shell until the first time "x" is hit or campaign end date configurable via source code change is reached 
- The message should read "Help Angular by taking a 1 minute survey!" (the text in the mocks has since been changed)

Desktop Only:
- Also click on "go to survey" button to navigate to survey

Mocks (text is outdated):

![aio-surveydesign_desktop-final](https://user-images.githubusercontent.com/2958442/34178941-d281d0b8-e4bd-11e7-874b-3b4cedad4b21.png)
![aio-surveydesign_staticbar-mobile](https://user-images.githubusercontent.com/2958442/34226291-18ae6716-e57e-11e7-9abd-f7ad51061796.png)

**Comment by IgorMinar** [comment]
We can use local storage to keep the info about whether the campaign has been dismissed already once or not.

**Comment by petebacondarwin** [comment]
I can work on this tonight

**Comment by jiangjianyu** [comment]
I don't like this suggest.You can make a survey on stackoverflow.
