### ISSUE TITLE
Improve size tracking workflow and coverage

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21437]
Now that we've been tracking file sizes for quite a while and have a better idea about what is useful and what is an unnecessary productivity hit, it's time to make a few changes. I propose the following:

- [x] stop enforcing size limits for gzip7 and gzip9 in both aio and integration tests (we should keep on tracking the size just for informational purposes, but not actually enforce the limit via _payload_limits.sh files
- [x] include all aio *.js files in file size tracking but enforce the size only for js files in the critical path, namely 0.*.chunk.js (currently being renamed to embedded.module.*.chunk.js see #21351 )
- [x] we should also improve the size.angular.io app by
    - [x] not rendering lines for gzip9 and gzip7 (they add too much noise)
    - [x] adding 5.1.x and 5.2.x branches

**Comment by IgorMinar** [comment]
@tinayuangao could you please take a look at these?

**Comment by tinayuangao** [comment]
Updated our payload size app: 
1. Make gzip9 & gzip7 optional
2. Added other branches
3. includes all files

**Comment by gkalpak** [comment]
@IgorMinar, can this be closed? All boxes in your check list seem to be ticked.

**Comment by jelbourn** [comment]
Closing since this issue specifically seems to be obsolete.
