### ISSUE TITLE
RxJS v6 release + support

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21572]
Work breakdown:

- public api cleanup
    - entry-point cleanup
      - [x] refactor (ben) ReactiveX/rxjs#3145 + ReactiveX/rxjs#3223
      - [ ] docs
      - [x] backwards compatibility solution
      - [x] forward migration transform
      - [x] google3 LSC
  - public api typings cleanup
      - [x] refactor ReactiveX/rxjs#3328
      - [x] backwards compatibility solution
      - [x] forward migration transform
      - [x] google3 LSC (if needed)
  - runtime api changes
      - ~[ ] move Observable.lift to separate function~
      - ~[ ] abort controllers - required by WHATWG~
      - ~[ ] async iterators implementation~
      - ~[ ] improve stack trace~
- size (depends on public api cleanup)
  - [x] Webpack v4 `"side-effects":false` support
- productivity
  - [ ] move rxjs to bazel
- g3
  - [x] migrate away from `rxjs/add/operator`
    - [x] transform
    - [x] google3 LSC
  - [ ] remove local mods
  - [x] move g3 sync to copybara
  - [x] bring v6 to g3
- misc issues to resolve
  - [x] https://github.com/ReactiveX/rxjs/issues/3374 `fromPromise` creation method missing

**Comment by shyamal890** [comment]
Request to add work bullet point addressing https://github.com/angular/angular/issues/19705 issue

**Comment by IgorMinar** [comment]
@shyamal890 that's totally unrelated to rxjs (it's a forms feature request) and unfortunately something that will have to wait due to all the other changes going on. I expect that we'll take a closer look at forms after v6.0 is out.

**Comment by michaeljota** [comment]
I know that `rxjs` was in RC when integrated in Angular, but now that this is stable, is still the plan to integrate a new version of `rxjs` that is currently in RC? Or this will be postponed until `rxjs@6` is stable?

**Comment by sarunint** [comment]
What is stable? I believe both Angular and RxJS are still in release candidate.

**Comment by michaeljota** [comment]
Angular have several stable releases, and I wonder if this is something the team will wait for before launching stable `6`

**Comment by sarunint** [comment]
Current stable version of Angular, v5.x, depends on RxJS version 5.x, which is also stable.

I think RxJS and Angular will reach v6 stable at almost the same time. (Well, the RxJS lead is also on the Angular core team)

**Comment by MattiJarvinen-BA** [comment]
RxJS 6 is released @michaeljota https://github.com/ReactiveX/rxjs/releases/tag/6.0.0

I bet this issue is solved within a week.

**Comment by gwelr** [comment]
With the release of both Angular 6 and Rxjs 6, documentation is no longuer accurate. I saw the the work breakdown at the top of this ticket, but with the importance of Observable and Rxjs in Angular, I believe it is important to update the documentation. 

Eg: https://angular.io/guide/rx-library#observable-creation-functions is no longuer valid.

it should be: 
```ts
import { from } from 'rxjs';

// Create an Observable out of a promise
const data = from(fetch('/api/endpoint'));
// Subscribe to begin listening for async result
data.subscribe({
 next(response) { console.log(response); },
 error(err) { console.error('Error: ' + err); },
 complete() { console.log('Completed'); }
});
```

**Comment by alfaproject** [comment]
I still can't get rid of `rx-compat` because zone.js depends on it. @JiaLiPassion any ETA to refactor that?

**Comment by MattiJarvinen-BA** [comment]
@alfaproject what is your current zone.js version?

**Comment by JiaLiPassion** [comment]
@alfaproject, I am doing this now, I will try to make a test version next week.

**Comment by mat3e** [comment]
@gwelr I also got confused when using `fromPromise` inside the application generated with Angular CLI. I've created a pull request for a documentation update.

**Comment by gwelr** [comment]
@mat3e congrats for your first PR. And it has already been reviewed. It seems your alias is considered redundant (at least for the documentation). EG: 
> import { from as from, Observable, of } from 'rxjs';

should be 

> import { from, Observable, of } from 'rxjs';

**Comment by mat3e** [comment]
Yes, the alias was `fromPromise` and I changed it 🤦‍♂️ it is already fixed.

**Comment by alfaproject** [comment]
@JiaLiPassion it's been 6 months and I'm still requiring `rxjs-compat` because of unit testing. Any progress on that?

**Comment by JiaLiPassion** [comment]
@alfaproject, it has been merged into `zone.js` master, but please wait for the next `zone.js` release.

**Comment by pkozlowski-opensource** [comment]
We've been on RxJS 6.x for a while so I guess we can close this general issue. Please open new, focused issue(s) if there is any remaining work to be done.
