### ISSUE TITLE
Misc Framework improvements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21578]
Other things that don't fit elsewhere

- size related bits
  - ~[ ] remove dependency on RxJS from the core package~ - pushed out to v7
  - [x] #22027 optimize whitespace in templates by default
  - [x] #22054 remove dependency on webanimations polyfill
- [ ] i18n
  - ~[ ] runtime i18n (only for Ivy)~ wip, but won't be ready until v7
  - [x] #20385 Currency Pipe Changes
  - ~[ ] #20551 Arabic Dates in DatePipe not displaying correctly~ pushed out to later releases
  - [x] #20624 export locale data as commonjs instead of es2015
- ergonomics
  - [x] #20669 Warn if an unsupported future version of TypeScript is used
- ~[ ] (stretch) #20030 router scroll position restoration support~ - not ready, pushed to v6.1
