### ISSUE TITLE
CI infrastructure improvements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21709]
- [ ] github robot automates 5+ workflows
  - [x] enforce mergability rules via CI/commit status
  - [x] #21635 move issues to the backlog
  - [ ] #21711 regression escalation
- [x] move Angular unit tests over to CircleCI
- [x] move angular.io unit and e2e tests over to CircleCI
- [ ] improve size tracking
  - [ ] move overall unpinned size-tracking outside of angular/angular 
  - [ ] expand coverage to examples with forms and router and material
  - [ ] https://github.com/angular/angular/issues/21437 improve size tracking workflow and coverage
- [x] #21692 reflect and enforce doc ownership via pullapprove
- [ ] #20884 incremental code formatting

**Comment by csutorasr** [comment]
Are PRs allowed?

Is the purpose of the CircleCI equals to the travis, or can it be changed? E.g. making e2e and unit tests parallel.

May I create an issue for that to discuss?

**Comment by jelbourn** [comment]
Closing since this seems obsolete; we can track ongoing CI work in more specific issues.
