### ISSUE TITLE
angular.io improvements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21710]
- [x] examples available on Stackblitz
- [ ] reliability and performance improvements
  - [x] #19795 angular.io migrates over to @angular/service-worker@latest
  - [x] #21943 crash reporting (+ #22713)
  - [x] #22483 add prod monitoring via e2e tests
  - [x] add prod monitoring via google analytics alerts
  - [ ] revisit http2 push / link preload strategy
  - [x] #22872 refactor codebase to use rxjs pipeable operators
  - [x] #22872 update to Angular v6 (rc)
  - [x] update to Angular v6 (final)
- [x] new API templates for all symbol types
  - [x] #21715 class type (done?)
  - [x] interfaces (done?)
  - [x] functions (done?)
  - [x] enums (done?)
  - [x] consts (done?)
  - [x] type aliases (done?)
  - [x] #22702 pipes
  - [x] directives
  - [x] #22681 decorators
  - [x] NgModules
  - [x] packages / entry points
  - [x] #22634 refactor existing content to match the new jsdoc tags
- [x] SEO and crawlability improvements
  - [x] #21665 proper error handling
  - [x] #21317 404 handling
  - [x] #21377 fix bad redirects
  - [x] #21941 dynamically add the pre-emptive `noindex`
- [ ] usability improvements
  - [x] #19651 Fix print layout
  - [x] scheduling support for home page announcements
  - [ ] #22080 don't present stale content for frequently visited landing pages
- [ ] authoring improvements
  - [ ] reorg the aio/content folder to group examples, assets and md files together

**Comment by somombo** [comment]
also it appears https://angular.io/guide/change-log has outdated info
