### ISSUE TITLE
error TS2687: All declarations of 'observable' must have identical modifiers.

### ISSUE THREAD

**Issue by KayHS** [angular/angular#24245]
## I'm submitting a...
<pre><code>
[X] Other... Please describe:
Issue with build
</code></pre>

## Current behavior

When i `npm run build` my project in a docker environment i get the following error.

> ERROR in node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.
> node_modules/@types/node/index.d.ts(167,14): error TS2687: All declarations of 'observable' must have identical modifiers.

## Expected behavior

For it to build successfully, this error is stopping that.

## Minimal reproduction of the problem with instructions

`docker build -t demo:production --build-arg env=production .`

```
# Stage 0 - Pre-requisite: Based On Node.js to BUILD and compile Demo Angular App.

FROM node:8.11.2 as node

WORKDIR /app

COPY package.json /app/

RUN npm install

COPY ./ /app/

ARG env

RUN npm run build -- --configuration $env

# Stage 1 - Based On Nginx to have ONLY a compiled and PRODUCTION ready build.

FROM nginx:1.14

COPY --from=node /app/dist/ /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

```

## Environment

<pre><code>
Angular CLI: 6.0.0
Node: 9.8.0
OS: darwin x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0 (cli-only)
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0 (cli-only)
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v9.8.0
- Platform:  Mac

Others:
TS Config 

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

</code></pre>

**Comment by alfirin** [comment]
I got the same here.

**Comment by KayHS** [comment]
Fix is here. https://stackoverflow.com/questions/50639530/error-ts2687-all-declarations-of-observable-must-have-identical-modifiers

I was using ` @types/node to 10.3.0` i had to downgrade. Im now using `@types/node": "~8.9.4"`

**Comment by ericmartinezr** [comment]
Dup of https://github.com/ReactiveX/rxjs/issues/3769 (being tracked here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26198 mentioned in the issue), not related to angular.

**Comment by byblix** [comment]
Try this fix: In your package.json set this dependency > ` "@types/node": "10.0.4"` > npm i > ng serve.

**Comment by andreimcristof** [comment]
@byblix thank you but that showed the same error,however  user  recommended freezing "@types/node" to "10.1.2" on the related thread, and that one worked.

**Comment by zijianhuang** [comment]
There could be 2 solutions:
1. Go to rxjs/internal/symbol/observable.d.ts and hack:
```js
declare global  {
    interface SymbolConstructor {
        observable: symbol;
    }
}
```
to
```js
declare global  {
    interface SymbolConstructor {
        readonly observable: symbol;
    }
}
```

2. Or, in tsconfig.json, add this: 
```js
		"skipLibCheck": true
```

I would prefer the 2nd.

**Comment by petercunha** [comment]
This issue was fixed in the latest version of RxJS. Just run this command to update, then you should be able to compile your project:

```npm install --save rxjs```

**Comment by adappter** [comment]
I have still the same problem, my dependency versions are the latest:
    "rxjs": "6.2.1",
    "@types/node": "10.3.6"

ERROR in ../node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.

node_modules/@types/node/index.d.ts(169,14): error TS2687: All declarations of 'observable' must have identical modifiers.

**Comment by bfwg** [comment]
Tested, the below works.
```
    "rxjs": "6.2.1",
    "@types/node": "10.3.6"
```

**Comment by petercunha** [comment]
@adappter maybe you still have old dependencies still installed. Try:

```
rm -rf node_modules/
npm i
```

**Comment by agnaveen** [comment]
I got this issue today:

ERROR in ../../../../node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.


```
Angular CLI: 6.1.3
Node: 8.11.1
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.3
@angular/cli                      6.1.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3
```

and @types/node version = 10.5.7

Can I have some help please ?

**Comment by mlc-mlapis** [comment]
@agnaveen ... as I remember there was missing `readonly` ... in `readonly observable: symbol;`
```
/** Symbol.observable addition */
declare global  {
    interface SymbolConstructor {
        readonly observable: symbol;
    }
}
/** Symbol.observable or a string "@@observable". Used for interop */
export declare const observable: string | symbol;

```

**Comment by webwizrd** [comment]
Had the same error today. Moved to the following combination, which works for me:

- node v8.11.2
- angular 6.0.5
- rxjs 6.2.1
- @types/node 10.5.2

**Comment by mstickel** [comment]
My problem appears to have been that I had an import of `import 'rxjs/add/operator/finally';` in my Angular 6 app.  Removing this and replacing with the new pipe/finalize mechanism resolved the issue.

**Comment by LayZeeDK** [comment]
Use at least RxJS 6.3.0 if you want to stay on Node.js 8.x and use a corresponding `@types/node` version.
```
// package.json excerpt
"dependencies": {
  "rxjs": "^6.3.0"
},
"devDependencies": {
  "@types/node": "^8.10.0"
}
```

**Comment by PavelFoujeu** [comment]
@petercunha  answer solve this issue for me. 👍

**Comment by hvallenilla** [comment]
> I fixed the problem already.
> 
> What I did:
> 
> * I installed the working version for `rxjs 6.2.0` and `@types/node 10.1.4`
> * Push the working project and jenkins started to build
> * It failed at the test pipeline with the error message, that I'm using wrong import paths e.g. `rxjs/add/observable/of`
> * Fixing all tests with correct imports, e.g. `import {  of } from "rxjs";`
> * Updates to  `rxjs 6.2.1` and `@types/node 10.5.2`
> * Pushed again and the build worked

Thanks, fix my issue
