### ISSUE TITLE
[IVY] i18n runtime side

### ISSUE THREAD

**Issue by vicb** [angular/angular#24785]
There are a few things that need to be updated:
- [ ] `elementStart()` immediately followed by an `elementEnd()` has be change to `element()` (#24805)
- [ ] placeholder names in the maps should be quoted to prevent them from being renamed.  (#24805)
- [ ] the `tmplContainers` parameter to `i18nMapping` sounds wrong. Template containers do not have a name, seems like you are referring to the containee ?  (#24805)
- [ ] looking at the generated code, it seems that all `i18nMapping()` calls will be executed when the script is loaded instead of lazily when needed. Wouldn't it be better for perf to execute them lazily when needed ? (#24805)

### July 18 edits

- [ ] Change `i18nInterpolation(mapping, nbOfArg, ...args)` to `i18nInterpolation1(mapping, arg1)`, `i18nInterpolation2(mapping, arg1, arg2)` to match [non-i18n interpolations](https://github.com/angular/angular/blob/23dc9a90b0c7e82b23aabb7bf10aea11a14ffcd2/packages/core/src/render3/instructions.ts#L2422) ([#24805](https://github.com/angular/angular/pull/24805/commits/945e5338b9a1a71f3473867a589da4a4e2d1a4f2))
- [ ] Update the compiler design docs with the change
- [ ] Address the other items assigned to you in this design spec

### July 19 edits

- [ ] looking at the code I am wondering if changing the order of embedded templates in a translation would work, given that the instructions are pushed for each templates in the order they are seen in the translation. Please add tests for : changing the order of the template and removing (ie no using) a template in the middle. ([#24805](https://github.com/angular/angular/pull/24805/commits/143c36d5f89c7ad0e6128453c17dd8118cb756d8))

**Comment by ocombe** [comment]
> the tmplContainers parameter to i18nMapping sounds wrong. Template containers do not have a name, seems like you are referring to the containee ?

I'm refering to the `container(...)` instruction, which is supposed to have a name in the translations. But it's true that the first instruction in those embedded templates will have the same name in the translation

For example with the following html:
```html
<ul i18n>
  <li *ngFor="let item of items">value: {{item}}</li>
</ul>
```

The translation would be something like: `{$START_LI}valeur: {$EXP_1}{$END_LI}`, and the ivy instructions would be:
```ts
template: (rf: RenderFlags, myApp: MyApp) => {
  if (rf & RenderFlags.Create) {
    elementStart(0, 'ul');
    {
      // Start of translated section 1
      container(1, liTemplate, null, ['ngForOf', '']);  // START_LI
      // End of translated section 1
    }
    elementEnd();
    i18nApply(1, i18n_1[0]);
  }
  if (rf & RenderFlags.Update) {
    elementProperty(1, 'ngForOf', bind(myApp.items));
  }

  function liTemplate(rf1: RenderFlags, row: NgForOfContext<string>) {
    if (rf1 & RenderFlags.Create) {
      // This is a container so the whole template is a translated section
      // Start of translated section 2
      elementStart(0, 'li');  // START_LI
      { text(1); }            // EXP_1
      elementEnd();
      // End of translated section 2
      i18nApply(0, i18n_1[1]);
    }
    if (rf1 & RenderFlags.Update) {
      textBinding(1, bind(row.$implicit));
    }
  }
}
```

So `START_LI` represents both the `container` in the root template and `elementStart(0, 'li');` in the embedded template.
Do you want me to rename `tmplContainers` to `tmplContainees`? I think that `container` is still a better name.


> looking at the generated code, it seems that all i18nMapping() calls will be executed when the script is loaded instead of lazily when needed.

How would you lazily compute this? If it's executed in the template function, it'll be executed each time we create a new component with this template.
I could do something like:
```ts
if(!i18n_1) {
  i18n_1 = i18nMapping(...);
}
```

and keep a `let i18n;` at the top?

**Comment by vicb** [comment]
1) I think `template` is a better name

2) yes
