### ISSUE TITLE
Hosting a Web Component inside an angular app. Data binding and change tracking is not working.

### ISSUE THREAD

**Issue by SchneiderMK** [angular/angular#24901]
## I'm submitting (maybe) a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I've developed a web component with @angular/elements. When I'm hosting the web component inside an angular app, change tracking and data binding is not working.
Hosting the web component outside angular (plain html) works fine.

## Expected behavior
Web components should work in an angular app.

## Minimal reproduction of the problem with instructions
Due hosting on stackblitz is not possible, I've create a demo project to show the behavior.
https://github.com/SchneiderMK/angular-elements-demo

## What is the motivation / use case for changing the behavior?

We like to develop a micro frontend. The shell app and some parts of the micro services are developed with angular. We like to use Web Components to integrate the different components.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: V10.1.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by ardiadrianadri** [comment]
The same problem. I have an angular element that has several observables inside and a template that subscribes these observables through the async pipe. Even though the next event is triggered and the values are updated, the view is not changing.

 You can reproduce it in the next github repository, in the branch "table-element": 
 https://github.com/ardiadrianadri/table-elements/tree/table-element

**Comment by remackgeek** [comment]
A lot of your issue is the same one raised by @tnicola here: [fix(elements): initialization should run in ngZone (#24181)](https://github.com/angular/angular/pull/24185)

Change detection works with that, but there's still an issue with setting the initial value that isn't fixed by that.

**Comment by tnicola** [comment]
Hi @SchneiderMK and @ardiadrianadri , I faced exactly the same problem while I was working with @angular/elements as microfrontends in a Angular shell. The problem is that @angular/elements are Zoneless by default as @robwormald said. One could think that being in a Angular app, then change detection should always work but it doesn't. This is related to the "Change Detection lifecycle", each Angular app has it own, if for some reasons (*ngIf, *ngFor, *Routing or other events) we're dropped out from the element zone then CD won't work for that element. 
In order to get Change Detection working we need to run the element code in its own ngZone instance.

There's a PR opened for that. In the meanwhile, you can try the @remackgeek library: https://github.com/remackgeek/elements-zone-strategy that works great in all the cases!

**Comment by robwormald** [comment]
I believe this is corrected in the recent zone.js release. Closing, but please mention here if it doesn’t fix.

**Comment by searva** [comment]
Hi, I have followed this thread in order to fix the same issue. In my case, I have built a web component with angular 7 and drop it in a regular Angular 7 spa. Remark, that elements-zone-strategy its also needed and in my case I had to comment polyfills.ts to avoid to load zone.js (this is because the webcomponent js library already loads it), but webcomponents only works properly if it is dynamically inserted in dom.  If it is created, in line in a regular component template, initial property binding fails with an undefined value.

**Comment by antch** [comment]
Unfortunately this still appears to be an issue as of 7.2.14. For example:

```
var ce = document.createElement('my-ce');
ce.someProp = false;
someExistingElement.append(td);
```

When the Angular Element's `ngOnInit` is subsequently fired, the property is is undefined. Later, `ngOnChanges` fires with the property change from `undefined` to `false`.

In order to \*ahem\* protect anonymity I will not say who, but I just bumped into a presenter at ng-conf and they also were aware of this issue.

**Comment by Go4th** [comment]
If anyone has gone through using the element-zone-strategy and still facing the issue, do exactly what @searva  said and comment out the line in polyfills.ts that imports zone.js. Thanks searva.
