### ISSUE TITLE
Provide context for all runtime errors

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2992]
Currently when we throw an exception, we do not give the developer a lot of information. So you often see messages like this `No value accessor found for ''`. It is very hard for the developer to know what went wrong.

I think we should wrap user errors and add some context to where the error occured:

```
interface ErrorContext {
  componentInstance: any; // The context of evaluation
  componentElement: ElementRef;  // The host element of the component. 

  directiveInstance?: any; // The directive that caused a problem. Optional.
  element: Node;  // The element on which the problem occurred. 
  injector: Injector; // the injector of the element.

  expression?: string; //the expression that caused the problem
}
```

## Adding Context Automatically

- We already wrap exceptions triggered inside change detection into `ChangeDetectorException`. This exception should take an instance of ErrorContext. So when an exception happens in a binding, the developer we can see what binding threw, what was the context of evaluation, what element the binding was on. She can also hover over `element` in dev tools, and chrome will highlight the element on the page.

- We should wrap exceptions triggered by event handlers into `ChangeDetectorException` and supply an ErrorContext.

- We should provide ErrorContext to `InstantiationError`. So when an error happens in DI, the developer will see more than just: "Cannot find Service A".

This should cover a majority of errors developers see. 

## Adding Context Manually

We should also provide a way to obtain the context in a directive, so the developer can use it to throw exceptions that are not handled by change detection or directive instantiation. Maybe like this:

```
class MyDirective {
  constructor(errorContext: ErrorContext){}
}
```

## Todos

- [x] add error context to InstantiationError
- [x] add error context to ChangeDetectionError
- [x] add error when an event throw an error
- [x] adding context manually

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/07b9be798c1c0f8eb37788c80d2b0bffe87e6d82
