### ISSUE TITLE
Query redesign

### ISSUE THREAD

**Issue by rkirov** [angular/angular#3922]
This is a proposal for a redesign for the query API. It allows a directive to find other directives that are structurally its 'children'.

- A directive can query the children of the element it is placed on with `@ContentChild` / `@ContentChildren` (used to be @Query) and its view with `@ViewChild` / `@ViewChildren` (used to be @ViewQuery).
- When using @xxxChild the object received will be the desired element (or null if not found), when using @xxxChildren the object will be an ObservableArray.
- Queries will be recalculated when a structural change occurs (ng-if, ng-for), @xxxChild will be set to the new value, while @xxxChildren will notify via the observable API.
- The results will not be injectable, but rather set on declared properties by the framework.

Ex:
```javascript
@Component(...)
@View(...) 
class ListComponent {
  @ContentChild(ItemDirective)
  itemDirective: ItemDirective;
 }

@Component(...)
@View(...) 
class ListComponent2 {
  @ViewChildren(ItemDirective)
  itemDirectives: ObservableArray<ItemDirective>;
 }
```

The children directives will be set before the following callbacks are fired (https://github.com/angular/angular/issues/3863) - `afterContentChecked` for `ContentChild` and  `afterViewChecked` for `ViewChild`. 

Both query mechanisms do not go into further into component subviews. `ContentChild / ContentChildren` support configurable visibility as follows :
- `descendants: true` - all content descendants are considered
- `descendants: false` - only direct children of the querying directive are considered (default)
`ViewChildren` has no visibility configuration. Queries always skip the element on which the querying directive lives (similar to `DOM.querySelector`).

Implementation
- [x] implement lifecycle hooks (https://github.com/angular/angular/issues/3863)
- [x] hook up query update calls to the new hooks
- [x] add integration test for view query with var bindings (#3920)
- [x] remove query from forms API (#3962)
- [x] using view.elementInjectors internally instead of inj.children tree (closes #3625)
- [x] add `ContentChildren` and `ViewChildren` (#4237)
- [x] use Rx.Next for ObservableArray
- [x] move declaration to @Component field and using setters
- [x] implement ContentChild and ViewChild
- [x] remove self visibility from Query 
- [ ] optimize static single child
- [x] implement dynamic strategy for queryRefs

// cc @mhevery @vsavkin

**Comment by ericmartinezr** [comment]
If I'm allowed to ask, considering this point

`When using @xxxChild the object received will be the desired element (or null if not found), when using @xxxChildren the object will be an ObservableArray.`

What would happen if I use `@xxxChild` and in my template I have Nth-children what will `@xxxChild` do? Will return the first one found or an ObservableArray containing just one element? Will throw because it found more than one and doesn't know which one to return?

I say it would be better to keep the current functionality : if I have one or more elements, the `@Query` always returns an array. This way you can keep the `@xxxChildren` and forget about `@xxxChild`.

**Comment by vsavkin** [comment]
The only thing that is left is to remove the old API.
https://github.com/angular/angular/issues/4919
