### ISSUE TITLE
Expand size-tracking to include first-party Angular libraries

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#39310]
Currently the size tracking only captures holistic metrics (e.g. angular.io) and more granular example apps (hello world). We may want to track more granularly by building cases for:

- [ ] Hello world with forms
- [ ] Hello world with router
- [ ] Hello world with forms + router
- [ ] Hello world with forms + router + Angular Material

Replaces #21268,  #21269, #21270, #21271
