### ISSUE TITLE
Optimizing incremental compilation status tracker

### ISSUE THREAD

**Issue by JoostK** [angular/angular#40728]
This issue is created as a status tracker to implement an optimization for incremental compilations to enable more effective reuse of work from the previous compilation. The general idea is that decorated classes will be compared to their equivalent in the prior compilation and skip emit if nothing relevant has changed. There has been a working prototype in #39791 which implements this idea, which has since been refined to a simplified yet more effective approach.

This work aims to address #34867 and #40635. One initial improvement in response to #40635 is pending in  angular/angular-cli#19986 which avoids an inefficiency in Webpack's dependency mechanism resulting in a significant improvement of rebuild times. This work should take this one step further and avoid emit of files when their generated output could not possibly be affected by the change.

- [x] Implement semantic dependency graph and symbol comparison ([ngtsc/semantic-updates](https://github.com/angular/angular/tree/ngtsc/semantic-updates))
- [x] Refactor the registration of semantic symbols
- [x] Work on remote scoping scenarios
- [x] Address scenarios that may result in broken type-check-blocks
  - [x] Generic type parameters
  - [x] Changes to inheritance chains
  - [x] Changes to type-checking metadata
- [x] Test various scenarios:
  - [x] Update expectations for existing tests.
  - [x] Test behavior in combination with errors in the program.
  - [x] Test behavior in combination with external declarations.
  - [x] Changing an NgModule into a Component, and all other relevant combinations.
  - [x] Introducing and breaking cyclic component includes to verify remote scoping.
  - [x] Classes that are exported under a different name
  - [x] Add template type-checking tests for generic type parameters
  - [x] Add template type-checking tests for inline ctors
  - [x] Add template type-checking tests for various metadata properties
  - [x] Add template type-checking tests for inheritance
- [x] Update ngcc tests (i.e. fix build errors)
- [x] Update incremental rebuild documentation.
- [x] Review

**Comment by Splaktar** [comment]
Thank you for prioritizing this!

**Comment by vthinkxie** [comment]
Thanks @JoostK
