### ISSUE TITLE
The animations docs need to be improved regarding elements entering and leaving (`:enter`, `:leave`)

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#44253]
## Issue Description

Currently the animations documentation doesn't specify clearly what elements are animatable via `:enter` and `:leave`

As far as I can tell the only text saying something of that sort is this: https://angular.io/guide/transition-and-triggers#use-of-ngif-and-ngfor-with-enter-and-leave which I believe it's vague at best :sweat: 

Not even the [query api docs](https://angular.io/api/animations/query), nor the [transition api docs](https://angular.io/api/animations/transition) say anything about the restrictions/rules around entering/leaving elements

## Contex

This has lead to misunderstanding and issues being opened (such as #30477)

Related to this, not even the [animations live example](https://stackblitz.com/run?file=src/app/app.component.ts) works smoothly as it doesn't seem to take this aspect into account (for example try to navigate from `Filter/Stagger` to `Open/Close`, you will see that the yellow box's animation doesn't get triggered as you'd expect it to)

## Solution

The documentations should be improved and should make very clear what `:enter` and `:leave` applies to

## Relevant points

 - the only elements considering by `:enter` and `:leave` are host elements and elements with structural directives
 - `query` is clearly being effected (as you can see in the discussion in #30477), I think that `transition` could be the same, other animation's api functions could also be affected by this so this should be investigated I believe
 - both the api docs and the animation guides should make clear what elements are considered as entering/leaving
 - the animations live example should be improved so that it works more smoothly/correctly and it also exemplifies the entering/leaving nuances (suggestion: with the live example's improvement, a docregion can be added with a section in the animations guide showcasing how to properly query entering elements, especially during routing)

## TODOs

 - [x] improve the query api docs with the entering/leaving elements information
 - [x] improve the transition api docs with the entering/leaving elements information
 - [x] improve the animations live examples (in regards to entering/leaving elements)
 - [x] improve the general animations guide with the entering/leaving elements information

**Comment by dario-piotrowicz** [comment]
@petebacondarwin I would love to take this one on, could I be assigned to it? :bow: :pray:

**Comment by dario-piotrowicz** [comment]
@petebacondarwin thanks :smile:

**Comment by dario-piotrowicz** [comment]
### Note to self (and to whoever would want to chip in :stuck_out_tongue_winking_eye:)

`transition`s actually work differently on with `:enter` compared to `query`, there, even non-move elements get animated as entering ones

Fixing that so that `transition`s work like `query`s is not that difficult (https://github.com/dario-piotrowicz/angular/commit/0e6e9e15fd9d715c132fe74ab5643b7b8eda414b) but I think it would be very breaky and possibly not worth the effort/breakage, so I think we should just keep it as is but at least make the difference quite clear in the docs

**Comment by dario-piotrowicz** [comment]
I believe this issue has been done :slightly_smiling_face: 

@jessicajaniuk please let me know if you disagree :slightly_smiling_face:
