### ISSUE TITLE
Remove index_static.js from hello_world example.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#495]
Once the dart transformers work, we should be able to remove [`index_static.js`](https://github.com/angular/angular/blob/master/modules/examples/src/hello_world/index_static.js) from the source code since transformers will now be generating the file.

Requires issue #: 
 - [x] #496 Transformers create constructor stubs
 - [ ] #497 Tree shake constructor stubs
 - [x] #498 Transformers include annotations for each constructor stub
 - [x] #500 Generate setter stubs for the Directives
 - [ ] #501 Parse HTML templates to extract stubs from expressions & statements, then generate getters/setters stubs for reflection
 - [x] #503 Mock out DOM API so that compiler can execute outside the browser
 - [ ] #502 Generate Change Detection classes instead of getter setter stubs from #501, #503.
 - [x] #700 Remove import of dart:mirrors

**Comment by kegluneq** [comment]
+ [ ] https://github.com/angular/angular/issues/700 Remove import of dart:mirrors
