### ISSUE TITLE
Angular 2: Generate DI, Locals, Queries

### ISSUE THREAD

**Issue by tbosch** [angular/angular#6270]
The goal is to codegen DI as `new` calls, and in the end don't need any reflective information from `@Component` / `@Directive` / `@View` annotations at all.

An internal prototype showed that this approach gives us great wins for bootstrap time.

Changeset 1: Codegen DI, query and pipes
- [x] Change ViewCompiler to also generates DI, Locals and Queries #6301 (@tbosch)
- [x] Change Dart transformer to collect meta information about DI and Queries #6298
- [x] Create integration tests for all injector and element injector unit tests #6299
- [x] Create integration tests for all ChangeDetection tests #6299

Changeset 2: Remove reflector
- [ ] Codegen App Injector / remove ReflectiveInjector and Reflector #8997

**Comment by tbosch** [comment]
Subtasks:

- [ ] Support tests that use precompiled components
    - [ ] Support new dart test package #2783
    - [ ] Allow to mock out components in codegen mode #6276

**Comment by pkozlowski-opensource** [comment]
@tbosch is anything remains to be done to be here or could this one be closed?
