### ISSUE TITLE
Add support for optional @Parent and @Ancestor

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#675]
# Required Work

- [ ]  Injector look up is either in `ElementInjector` or `Injector`, we can't cross boundaries, determined at compile time. #708
- [ ] `@Optional` only makes sense for `ElementInjector` #708
- [ ] `directives` property of `@Template` can now take `Binding` (verify) #709
- [x]  Support `toAlias` binding in both `ElementInjector` and `Injector` #710
- [ ] remove `ligthDomServices` and `shadowDomServices`. #711

===============================================================

Here are a couple of use-cases for optional `@Parent` and `@Ancestor` injection:

#### Custom radio-button.

A radio-button can appear both inside of a radio-button-group or standalone. When inside of a group, the user interacts with the radio-buttons as a group (one focus stop + keyboard shortcuts). As standalone, the radio-buttons can be placed anywhere, such as inside the cells of a `<table>`. The MdRadioButton needs to be able to use an injected MdRadioGroup and register itself, but use a different code path when that `@Parent` is absent.
```html
<md-radio-group>
  <md-radio-button>Star Wars</md-radio-button>
  <md-radio-button>Star Trek</md-radio-button>
</md-radio-group>
```
```html
<md-radio-button name="music">The Rolling Stones</md-radio-button>
<!-- some arbitrary html -->
<md-radio-button name="music">The Beatles</md-radio-button>
```

#### Theming
Currently, ng-material lets you specify a theme for a section of the app using `md-theme`:
```html
<p>Here is some default-themed content</p>
<div md-theme="ponies">
  Everything inside here uses the "ponies" theme.
</div>
```

Applying a theme is obviously optional, so having an optional `@Ancestor` injection would be necessary to check if there is a theme applied to the element.

**Comment by mhevery** [comment]
1. Injector look up is either in `ElementInjector` or `Injector`, we can't cross boundaries, determined at compile time.
2. `@Optional` only makes sense for `ElementInjector`
3. `directives` property of `@Template` can now take `Binding` (verify)

**Comment by mhevery** [comment]
@jelbourn is this resolved? (I believe so.)

**Comment by jelbourn** [comment]
Closed by https://github.com/angular/angular/commit/ba0a1ec459cbf03879084e91766d28cd86e14ee2
