### ISSUE TITLE
Tracking: Animations

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7478]
_Blocking_
- [x] CSS parser
- [x] Triggering animations on DOM events (enter, leave, addClass, setAttribute)
- [x] Animations as sequences (groups and linear lists)
- [ ] Parsing and utilizing CSS data in animations (classes, keyframes and inline styles)
- [x] Web Animations driver integration

_Stretch_
- [ ] CSS Driver Integration
- [ ] Restoring CSS styles to initial or a snapshot state within CSS
- [ ] Querying Children for animations
- [ ] Staggering multiple animations
- [ ] Transforming styles with JS-level calculations
- [ ] Component-level player access with callbacks and scrubbing
- [ ] Detecting click events and embedding input into animation data
- [ ] Custom stagger and JS animations functions
- [ ] Media Query support in CSS and Sequences
- [ ] Anchoring
- [x] Works with WebWorkers
- [ ] Works with Native Renderers

**Comment by fxck** [comment]
What's the current state of animations, is it usable? I don't see it being used pretty much anywhere in the wild(not in libs libs ng-bootstrap or material2 either and when they do animations, it's not using angular animations). No blog posts, tutorials either..

**Comment by Brocco** [comment]
I have used it a little in my application (not public) but you can find an example usage here: https://github.com/teropa/elseq/blob/master/src/elseq.component.ts

**Comment by fxck** [comment]
Yeah I've seen that one, what I meant were more practical examples.. like any material design effect really.

**Comment by intellix** [comment]
this ancient issue can be closed now? :)
