### ISSUE TITLE
Tracking: i18n support

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7480]
**Infrastructure**
- [x] I18n: Implement Message Merger #7469
- [x] Create a dart tool to extract all messages for an app #7468
- [x] Implement Message Extractor #7467 
- [x] Wire Up Message Merger Into Dart Transformers #7470 
- [x] Convert `{{{ }}}` into directives

**Directives**
- [x] `ngPlural` directive: https://github.com/angular/angular/pull/7415
- [X] `ngSelect` directive:  Same behavior os `ngSwitch` no action.
- [X] `i18nPlural` pipe: 59629a0801fcfa1e61410d3dee6717c208b66e7f
- [*]  `i18nSelect` pipe: 59629a0801fcfa1e61410d3dee6717c208b66e7f 

**Misc:**
- [Angular and Internationalization: The New World](https://docs.google.com/document/d/1mwyOFsAD-bPoXTk3Hthq0CAcGXCUw-BtTJMR4nGTY-0/edit#heading=h.ixg45w3363q)
- [ICU Formatted Messages](http://userguide.icu-project.org/formatparse/messages)

**Comment by steida** [comment]
Hi, just a quick question. Will Angular 2 support run-time locale change? I mean something like https://este.firebaseapp.com/intl. Thank you.

**Comment by smajl** [comment]
@steida If not out of the box then I guess there will be 3rd party modules just like for Angular 1.x:
https://github.com/lgalfaso/angular-dynamic-locale

**Comment by fojt** [comment]
@steida https://github.com/ocombe/ng2-translate

**Comment by ocombe** [comment]
Yes you can use ng2-translate for now. Once the official i18n support for Angular 2 is complete I will either deprecate the lib or keep it if it fulfills other needs not covered by i18n.

**Comment by markharding** [comment]
@ocombe are you following the same template syntax as Angular2 will? I'm just wondering how much of a huge refactoring job it will be to move over in the future.

**Comment by ocombe** [comment]
No, I'm following the template syntax from angular-translate. There was no angular 2 syntax when I started this lib :)

**Comment by laco0416** [comment]
All tasks above seem completed on beta.13.
And, on Twitter, AngularJS official said; "The i18n support begins in this release". Really?

https://twitter.com/angularjs/status/715390643732762625

We need some docs to implement i18n into my application!

**Comment by AmineAfia** [comment]
Still no docs for the i18n support ?

**Comment by ocombe** [comment]
In this week's meeting notes they said:
> I18n
> Template string extraction and pluralization directives complete.
> Several more minor steps required to make it usable in real projects.
> Requires completion of Change #1 in Core to work.
