### ISSUE TITLE
Tracking: Language services provide intellisense for Angular 2 templates

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7482]
We plan to use the extension API tracked by [TypeScript issue #6508](https://github.com/microsoft/typescript/issues/6508) to provide language services inside template strings of a `@Component` decorator as well as reuse these services in loose HTML files.
## Features

The features we plan to support are,
- Syntax and semantic code highlighting
- Syntactic and semantic error reporting
- Completion lists for HTML built-in elements and referenced directives
- Completion list for data-binding expression
- Parameter lists for data-binding function calls
- Go-to definition on attributes, elements and binding expressions

A prototype of these features was already implemented by Microsoft as part of the work to validate the [their extensibility](https://github.com/microsoft/typescript/issues/6508) and the referenced issue has an animated GIF that shows the prototype in action.

This work is to use the Angular 2's template parser, instead of a custom parser, as well as using the Angular 2 offline-compiler metadata to describe the components allowing libraries (such as Material) to be self-describing.

Additional features (probably post-final):
- Source formatting and indentation support
- Rename of directive and attributes
- Quick fix to add missing directives `Component` decorator
## Editor support

Editors that support configuring TypeScript extensions will be able to use the Angular 2 extensions for template strings with no additional changes.

Editors will need to be modified to integrate the Angular 2 language service for loose HTML files similar to how TypeScript is integrated for use in .ts, .d.ts and .tsx.

This work will extend the TypeScript node server and VS Code to support both the Angular 2 extension and loose HTML files. 
#### Extending TypeScript

**Tasks**:
- [ ] Contribute to [TS#6508](https://github.com/microsoft/typescript/issues/6508) to help it land in TypeScript.
- [x] Modify `tsserver` to load _TypeScript Extensions_. (see https://github.com/Microsoft/TypeScript/pull/9038)
- [x] Contribute to VS Code to enable it to load _TypeScript Extensions_. (https://github.com/Microsoft/TypeScript/pull/9038, no VS Code changes needed)
- [ ] Assist other editors in supporting _TypeScript Extensions_ in general and Angular 2's extension in particular.

**Problem**: Angular 2 templates can be specified using a string literal or string template inside a TypeScript file. Providing language services for these strings requires TypeScript's language service to delegate calls to `LanguageService` to the Angular 2 language service.

**Soltuion**: Use the proposed extensibility interface provided by [TypeScript](https://github.com/microsoft/typescript/issues/6508). Help evangelize the extension API to editors that support TypeScript.
#### Syntax Highlighting

**Tasks**:
- [ ] <s>Augment the result of `getEncodedSemanticClassifications` with Angular 2 classifications using `HtmlLexer`.</s> Using .tmLanguage instead.

**Problem**: Produce `ClassifiedSpan[]` for ranges that intersect with a Angular 2 template. This requires determining if the span is in a template string which itself requires a semantic analysis of the TypeScript module to determine if the string is in a `@Component` decorator.

**Solution**: Only return Angular 2 syntactic classification in `getEncodedSemanticClassifications` because the semantic analysis of the TypeScript module is already available. To produce the spans, scan the `ClassifiedSpan`s returned by TypeScript and determine if any strings contained in the result are candidates. Use `HtmlLexer` to produce lexical tokens from the string and generate `ClassifiedSpan`s from the tokens.
#### Semantic Highlighting

**Tasks**:
- [ ] <s>Augment the result from _Syntax Highlighting_ with semantic information from the `TemplateParser` AST.</s> Using tmLanguage file instead.

**Problem**: Allow highlighting directives with a different color from built in HTML elements and attributes.

**Solution**: Use Angular 2's `TemplateParser` to produce a template AST and augment the classifications produce during Syntax Highlighting using information from this AST.
#### Diagnostic Messages

**Tasks**:
- [x] Invoke the `TemplateParser` on template strings and augment the result of `getSemanticDiagnostics()`.
- [x] Generate the template code for the template AST and augment with the diagnostics from the generated modules.

**Problem**: Produce error and warning messages for Angular 2 templates in `.ts`.

**Solution**: Invoke the Angular 2 `TemplateParser` on template strings in TypeScript modules and augment the result of `getSemanticDiagnostics()` with the result. Even syntax errors are delayed until `getSemanticDiagnostics()` because determining if a string is a Angular 2 template requires TypeScript semantic analysis.

**Problem**: Produce errors produced by code generated from a template. 

**Solution**: Invoke the offline compiler to produce the corresponding TypeScript for a template. Produce a secondary `LanguageService` for a project that now includes the generated code and augment the result diagnostics from the generated module.

**Alternative**: The proposed solution might take significant time and resources because it requires instantiating an additional TypeScript language service which potentially could double the memory and time to respond to language service calls. Alternately the expression AST could be typed directly against the TypeScript symbols and error messages produced without invoking a secondary language service. The current proposal is simpler but the alternative should be considered if performance and memory are an issue for the proposed solution.
#### Template Completions

**Tasks**:
- [x] Produce completion lists for element names.
- [x] Produce completion lists for attribute names.
- [x] Produce completion lists for attribute values from attribute type.
- [x] Produce completion lists for binding expressions.
- [x] Produce completion lists for interpolation expressions.
- [x] Produce parameter help for data-binding function calls.

**Notes**: All solutions begin by producing a `TemplateParser` AST and determine where in the AST the position requested corresponds to. All built-in HTML elements and attributes are treated as a built-in list of directives to avoid special casing HTML.

**Problem**: Produce completions lists for element names.

**Solution**: If the position is where an element is expected produce a list of available element selectors from the referenced directives.

**Problem**: Produce a list of attributes names.

**Solution**:  If the position is where an attribute name is expected produce the list of available attribute selectors that could match the current element. 

**Problem**: Produce list for attribute values from attribute type.

**Solution**: If the position is where an attribute value is expected determine the type of the attribute by requesting the type from TypeScript, produce the completion list from the types member symbols.

**Problem**: Produce completion lists for binding expressions.

**Solution**: If the position is where a binding expression is expected generate the corresponding template code and request a completion list from the corresponding location in the generated code from an internal TypeScript language service.  _See Alternatives in **Diagnostic Messages** for an alternative to the code generation approach and conditions for pursuing the alternative._

**Problem**: Produce completion lists for interpolation expressions.

**Solution**: If the position is where an interpolation expression is expected treat it like a _binding expression_ above.

**Problem**: Produce parameter help for data-binding function calls.

**Solution**: If the position is where a binding expression or interpolation expression is expected use the technique in _binding expressions_ above but requires a parameter list instead of a completion list from the language service.
#### Go to definition
- [x] Go to definition of an element name.
- [x] Go to definition of an attribute name.
- [x] Go to definition of an attribute value.
- [x] Go to definition of an binding expression.
- [x] Go to definition of an interpolation expression.

**Problem**: Determine location that defines a template element.

**Solution**: Use the same technique as is used in _Template Completions_ for the corresponding request but request references from TypeScript instead generating a completion list.
#### Sharable metadata

**Tasks**:
- [x] Persist `@Component` and `@Pipe` decorator information not available in `.d.ts` files. (#7763)
- [x] Create a shareable metadata reader for extracting information from a TypeScript AST and/or persistent data. (#7763)
- [x] Create a static reflector that allows the parser to use the persistent metadata. (#7813)

**Problem**:  Parsing an Angular 2 template relies on information provided using decorators. These decorators, however, are discarded when TypeScript produces a `.d.ts` file. The language services need a way to retrieve this information for modules for which it only has `.d.ts` files.

**Solution**: Write the decorator information discarded by TypeScript into a `.metadata.json` file that can be read by the language services. This is will be produced for Angular by the Angular build and for other libraries, such as Angular Material, by the Angular CLI when packaging the module for deployment.

**Alternative**: The metadata could be derived by loading the referenced modules. However this requires executing the modules thus requiring the language service to execute arbitrary third-party code directly. In many contexts, this would be an unacceptable risk. Also, some modules might have dependencies that could not be loaded in all contexts the language service must run such as modules with a browser dependency running in the tsserver. The proposed solution does not rely on executing third-party code so does not expose the language service to running potentially unready, incompatible, and/or unreliable code with unintended side-effects just to extract metadata information. Also, `.metadata.json` files can be written by a system that does load the modules and extracts the metadata information allowing the module to be loaded in a controlled environment outside the language service.

**Comment by chuckjaz** [comment]
We plan to use the extension API tracked by [TypeScript issue #6508](https://github.com/microsoft/typescript/issues/6508) to provide language services inside template strings of a `@Component` decorator as well as reuse these services in loose HTML files.

## Features

The features we plan to support are,
- Syntax and semantic code highlighting
- Syntactic and semantic error reporting
- Completion lists for HTML built-in elements and referenced directives
- Completion list for data-binding expression
- Parameter lists for data-binding function calls
- Go-to definition on attributes, elements and binding expressions

An prototype of these features was already implemented by Microsoft as part of the work to validate the [their extensibility](https://github.com/microsoft/typescript/issues/6508) and the referenced issue has an animated GIF that shows the prototype in action.

This work is to use the Angular 2's template parser, instead of a custom parser, as well as using the Angular 2 offline-compiler metadata to describe the components allowing libraries (such as Material) to be self-describing.

Additional features (probably post-final):
- Source formatting and indentation support
- Rename of directive and attributes
- Quick fix to add missing directives `Component` decorator

## Editor support

Editors that support configuring TypeScript extensions will be able to use the Angular 2 extensions for template strings with no additional changes.

Editors will need to modified to integrate the Angular 2 language service for loose HTML files similar to how TypeScript is integrated for use in .ts, .d.ts and .tsx.

This work will extend the TypeScript node server and VS Code to support both the Angular 2 extension and loose HTML files.

**Comment by mhevery** [comment]
@chuckjaz this is great (I moved your comment to the description). Could we add some checklist to it of smaller milestones? See: https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by mhevery** [comment]
Very nice! Thanks @chuckjaz!

**Comment by billti** [comment]
Sweet! Just a note on the **Syntax Highlighting** section above - currently VSCode (as well as Sublime Text) use TextMate grammars for syntax highlighting, so having an AST available doesn't help there. I'm not sure if/when those editors plan to provide more programatic control over syntax highlighting.

FWIW: I did a [simple TextMate grammar update](https://github.com/billti/TypeScript-TmLanguage/commit/7e62410b49df49e37d53e1759c5757547c5f9258) while prototyping to provide some rudimentary syntax highlighting if the property is a JavaScript template string for an object property named `template`, or was preceded by a marker comment (e.g. `/** @html */`). 

Note that I found the JsDoc type marker helpful (for syntax highlighting at least) as in several samples I saw, devs would use a pattern like the below, which is a challenge to tool for the template string. Hopefully with better tooling this will become less of a thing.

```typescript
// comp.ts
import {tmpl} from './mytemplate'

@Component({
  template: tmpl
  // etc..
})
export class SomeComp { }

// mytemplate.ts
export const tmpl = /** @html */ `<div>Some component here</div>`
```

**Comment by chuckjaz** [comment]
@billti How do you get VSCode to read the updated grammar?

**Comment by billti** [comment]
For development/testing, I just copy it over (e.g. on a Mac `cp "/Users/bill/src/TypeScript-TmLanguage/TypeScript.tmLanguage" "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/syntaxes/TypeScript.tmLanguage"`.

I don't believe VS Code has a supported way to extend built-in grammars yet, so we'd need to update the official one, or get some type of support added.

**Comment by angelozerr** [comment]
@chuckjaz @mhevery @billti many thank's for this great feature! I'm very excited to integrate your feature inside Angular2 Eclipse https://github.com/angelozerr/angular2-eclipse/wiki/Getting-Started

Have you an idea which release of TypeScript will include tsserver plugin extension and which release of angular2 will provide plugin language service for angular2?

Many thank's for your answer.

**Comment by chuckjaz** [comment]
@angelozerr I would be happy to work with you to get this into Eclipse. I currently have early version of this working for external templates (instead of template strings) [here](https://github.com/chuckjaz/angular/tree/ls-plugin) with the VS Code integration [here](https://github.com/chuckjaz/vscode-ng-template-service).

Neither is ready for prime time yet but we are getting closer.

I am currently planning to support template strings using the hooks in VS Code instead of waiting on the hooks to be available in TypeScript. i believe hooking into TypeScript is the right long term solution but using VS Code hooks is more expedient.

**Comment by angelozerr** [comment]
> @angelozerr I would be happy to work with you to get this into Eclipse.

Great thanks!

I'm using tsserver inside typescript.java. If I understand well, it's not possible today. You provide a Language Server for Angular2. So if I want to use your work, I need to develop a Java client which consumes your angular2 language server, is it that?

I would like really using tsserver, but perhaps I need to wait for the extensibility of TypeScript?

**Comment by chuckjaz** [comment]
I believe you are right. You need to create another client.

Extending tsserver is only half the solution. It would provide completions for template strings but not inside of loose template files. The project referenced will provide completions in both contexts.

**Comment by angelozerr** [comment]
> I believe you are right. You need to create another client.

I would like to avoid doing that and using tsserver because:

 * it's more clean and avoid doing 2 clients (one for angular2 TypeScript editor and one for angular2 template) 
 * best performance, because you avoid parsing twice the same TypeScript file (one to provide completion inside TypeScript editor and one for template).

> Extending tsserver is only half the solution. 

Why?

> It would provide completions for template strings but not inside of loose template files.

tsserver should be able to parse ml files, no?

**Comment by chuckjaz** [comment]
The current proposal for the extensibility model does not extend it to other file types. It will still only provide services for '.ts' or similar files.

**Comment by angelozerr** [comment]
> I agree with you about avoiding multiple services. We are currently working with Microsoft to be able to unify the servers 

Great!

> but that is probably not going to happen this year.

Ok if I understand, If I wish to use tsserver with your work, it will work only with *.ts files. I think it's a good start.

**Comment by chuckjaz** [comment]
I have update the content of the original message to reflect the current state of the language service.

**Comment by fxck** [comment]
There was a little demo about this on ng-europe, and I remember someone on the team panel saying it's basically ready, any news?

**Comment by chuckjaz** [comment]
@fxck I am getting ready to add the language-service module to `@angular` from my repository (https://github.com/chuckjaz/angular/tree/ls-plugin). It should go in sometime this week. It was not ready for 2.2 so I delayed it until 2.3. The PR referenced above should be the last change I need to Angular to be able to commit.

I would not say it is "basically ready", however. It is in an alpha state and will be checked into the `@angular` sources as experimental. It will follow the same SemVer semantics as the rest of Angular  with the experimental exemption for deprecation.

The VS Code extension will probably not make it this or next week (given it is a short week) as I still have some significant work to do in the extension.

**Comment by fxck** [comment]
@chuckjaz looks like support in angular landed, are you going to put that extension in the marketplace?

**Comment by chuckjaz** [comment]
Working on it. I plan to make a side loading version of the VS Code extension available this week. I need more testing to feel comfortable adding it to the marketplace.

**Comment by prigara** [comment]
WebStorm integration is coming in WebStorm 2017.1 Early preview around December 19th.

**Comment by geelus** [comment]
Hi chuckjaz
This would be awesome! Any updates yet?

**Comment by montella1507** [comment]
I am rly looking forward for that extension :-)

**Comment by kukjevov** [comment]
Hi, 
i tried this extension version 0.0.10, which is available here https://github.com/chuckjaz/vscode-ng-template-service/releases it is working with some bugs. But as far as i seen it works only for inline templates. Will the final version work also for standalone .html templates ?

**Comment by chuckjaz** [comment]
It should also work with stand-alone templates if the template is referenced by a component.

**Comment by geelus** [comment]
Didn't work on VSCODE.
Here is the log:

13/12/2016 4:20:53 AM - Microsoft VSIX Installer
13/12/2016 4:20:53 AM - -------------------------------------------
13/12/2016 4:20:53 AM - Initializing Install...
13/12/2016 4:20:53 AM - Extension Details...
13/12/2016 4:20:53 AM - 	Identifier         : ng-template
13/12/2016 4:20:53 AM - 	Name               : Angular Language Service
13/12/2016 4:20:53 AM - 	Author             : Google
13/12/2016 4:20:53 AM - 	Version            : 0.0.10
13/12/2016 4:20:53 AM - 	Description        : Editor services for Angular templates
13/12/2016 4:20:53 AM - 	Locale             : en-US
13/12/2016 4:20:53 AM - 	MoreInfoURL        : 
13/12/2016 4:20:53 AM - 	InstalledByMSI     : False
13/12/2016 4:20:53 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
13/12/2016 4:20:53 AM - 
13/12/2016 4:20:53 AM - 	SignatureState     : Unsigned
13/12/2016 4:20:53 AM - 	Supported Products : 
13/12/2016 4:20:53 AM - 		Microsoft.VisualStudio.Code
13/12/2016 4:20:53 AM - 			Version : 
13/12/2016 4:20:53 AM - 
13/12/2016 4:20:53 AM - 	References         : 
13/12/2016 4:20:53 AM - Signature Details...
13/12/2016 4:20:53 AM - 	Extension is not signed.
13/12/2016 4:20:53 AM - 
13/12/2016 4:20:53 AM - Searching for applicable products...
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Premium 2013 
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Professional 2013
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Professional 2015
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio Community 2015
13/12/2016 4:20:55 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
13/12/2016 4:20:55 AM - Found installed product - Global Location
13/12/2016 4:20:55 AM - Found installed product - ssms
13/12/2016 4:20:55 AM - Found installed product - ssms
13/12/2016 4:20:55 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by chuckjaz** [comment]
@geelus The log appears to be from Visual Studio, not Visual Studio Code. The .vsix referenced above only works in Visual Studio Code.

**Comment by geelus** [comment]
I thought this was because I was running visual studio. I closed VS Code and Visual Studio but the error is still the same. "The extension is not installable on any currently installed products".

**Comment by chuckjaz** [comment]
Please file an issue in https://github.com/chuckjaz/vscode-ng-template-service/issues

**Comment by chrissena** [comment]
@geelus (you need to install it from within VSCode by clicking on the ellipses in extensions and finding the vsix file you downloaded)
![vscode install](https://cloud.githubusercontent.com/assets/6528986/21148177/52e9dbbc-c14f-11e6-8a77-70254a84f47c.png)

**Comment by geelus** [comment]
@chrissena Thank you so much! It works now and it's awesome!

**Comment by chuckjaz** [comment]
The repository for the vscode extension has moved to its permanent home: https://github.com/angular/vscode-ng-language-service. Please reporting issues to this repository.

**Comment by mhevery** [comment]
@chuckjaz should this issue be closed?

**Comment by chuckjaz** [comment]
Yes.

**Comment by angelozerr** [comment]
@chuckjaz I have started to integrate @angular/language-service inside Eclipse and it starts working like a charm, great work!

I would like to know:

 * where is the best place to create issues for @angular/language-service. I would like to create issues to support rename, references features, codeFixes. I think thoses issues should be created inside https://github.com/angular/angular/issues but I would like just to have confirmation.
 * it should be very cool if we could have a RoadMap page like https://github.com/Microsoft/TypeScript/wiki/Roadmap for @angular/language-service.

Thanks!

**Comment by DzmitryShylovich** [comment]
> where is the best place to create issues for @angular/language-service. 

https://github.com/angular/angular/issues

**Comment by davidTurczi** [comment]
Will it ever work on big Visual Studio? (not Code)

**Comment by chuckjaz** [comment]
> Will it ever work on big Visual Studio? (not Code)

That is the goal. I am collaborating with Microsoft to do this but we don't have a time frame as yet. The first step is to unify the servers (one process for TypeScript and Angular instead of the two today, due to more strict memory restrictions), which won't happen until after TypeScript 2.2.

**Comment by angelozerr** [comment]
> which won't happen until after TypeScript 2.2.

To fix this problem today, I'm updating tsserver by following the same idea than https://github.com/Quramy/ng-tsserver It's little ugly but it works. I'm developping a tslint language service like your angular language service at https://github.com/angelozerr/tslint-language-service

**Comment by chuckjaz** [comment]
@angelozerr That is terrific! That works in a large set scenarios.

However, you have to make compromises in how the information is presented as all the completions and diagnostics have to look like they came from TypeScript. I am collaborating with TypeScript to fix this by extending the completion kinds, allowing specifying a source for the diagnostic, etc. Also, we need to define the behavior of what happens when a file unknown to the interface is passed in as well as how to augment the server in such a way as to include template files when calculating the project, etc. None of these compromises we feel are are acceptable for a VS integration.

**Comment by angelozerr** [comment]
@chuckjaz thanks for this information. 

I have created https://github.com/angelozerr/tsserver-plugins which concat at runtime the JS which override createLangugaeService to load plugins declared in the tsconfig.json and a the tsserver.js which is hosted in the node_modules. Instead starting tsserver with typescript/bin/tsserver, you start with tsserver-plugins/bin/tsserver-plugins

**Comment by andrewrheingans** [comment]
@chuckjaz any update on when this will land in Visual Studio? Thanks!

**Comment by VovanSuper** [comment]
So, as of release of Angualar 6, is it at all valid project / is it undegoes any active development ?

**Comment by olivermuc** [comment]
There is also this autocompletion bug still present:
https://github.com/angular/vscode-ng-language-service/issues/258

Sincerely hope this get's addressed at some point. Or if someone could point out how to fix this locally, I'm even happy to do it myself.

**Comment by olivermuc** [comment]
Even if it's decided to not allow underscores in html template property autocompletes, could someone point out how to fix this in the code, I can only image this to be a couple of lines...
Thanks so much.
@chuckjaz

**Comment by jpike88** [comment]
@olivermuc @chuckjaz last activity on that repo was 3 months ago, and the plugin is plain broken. Is this going to ever be sorted? Just curious

**Comment by jpike88** [comment]
FYI I'm going to use this extension instead

https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.typescript-angular-plugin

**Comment by olivermuc** [comment]
I found a small hack/workaround to make it work. Will post a link shortly.

**Comment by olivermuc** [comment]
See here: https://github.com/angular/vscode-ng-language-service/issues/258
