### ISSUE TITLE
Tracking: Code generation for build step

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7483]
# Static analysis for TS apps, fallback plan for ES5/ES6

Use the same library code to invoke TS language services to collect the component metadata for the offline compiler as we use in Angular 2 Developer Services.

E.g.
```
@Component({
  selector: 'some-comp',
  ...
})
class SomeComponent {}
```

Would result into the metadata, independent of the implementation of the @Component decorator:
```
{
  selector: 'some-comp'
}
```

## Advantages:
Offline template compilation is fast in developer roundtrip since editor usecase requires low latency.

## Disadvantages:
Can't use the full power of the Decorators language feature. Probably need to detect and warn if user's code can't be statically analyzed.
Allowing users to write their own Decorator
We should avoid a first-party-only solution, where only the Decorators we've written work with the metadata collection.

## Options discussed:
- [ ] Add a meta-decorator, which describes the compiler metadata produced by a decorator.
- [ ] Develop a plugin mechanism so that user's decorators can publish the metadata produced by execution of their decorator
- [ ] What about ES5/ES6 users?
- [ ] Ship the template compiler in a version of angular binary. Add a $templateCache similar to angular1 to avoid XHR for template content. Template compiler becomes performance sensitive.
Write the tool from Option 1, but only use it for ES5/ES6 users. Maintenance of that tool likely worse, as it falls off our main support path.
- [ ] Require ES5/ES6 users to provide some statically analyzable data in their application, possibly by requiring a particular syntax sugaring for attaching annotations to classes/functions.

**Comment by alexeagle** [comment]
In https://docs.google.com/document/d/1nVDqnvtWeus1F2kQJIRnuXnGlNuA68j0vAvu6q9GR-8/edit
we decided not to pursue https://github.com/angular/angular/pull/7155

The reasoning is that we must be careful about supporting arbitrary eval() behavior, which is not statically analyzable. This will cause a difference in behavior with the editor tooling, which must be interactive responsive (<100ms) and therefore cannot execute the entire program in order to discover the directive metadata.

**Comment by alexeagle** [comment]
@robwormald @mhevery what is left to do on this issue? Do we need to document the workaround for JS-authored apps as suggested in the OP? Do we need to document the cookbook for the tooling downstream of `ngc`?

**Comment by IgorMinar** [comment]
I think that this can be closed. @mhevery ?
