### ISSUE TITLE
Compiler can run as a build step

### ISSUE THREAD

**Issue by mhevery** [angular/angular#760]
- [X] fix(core): workaround for circular dependencies in nodejs #716
- [X] refactor(change_detection): remove circular dependencies #712
- [x] Create DOM adapter so that compiler can execute outside the browser #503 
- [ ] Implement node.js DOM adapter (https://www.npmjs.com/package/html5)
- [x] Implement dart DOM adapter (https://pub.dartlang.org/packages/html5lib)
- [ ] ProtoView serializer / deserializer.

**Comment by mlaval** [comment]
For the node.js DOM adapter part, we could continue on the adapter used in my experiments, but it was based on https://github.com/inikulin/parse5
Any reason for pushing for https://www.npmjs.com/package/html5 please ?

**Comment by yjbanov** [comment]
I am familiar with neither. parse5 has more downloads and is hosted on GitHub. html5 is hosted on a custom server, it seems.

**Comment by yjbanov** [comment]
Closing this as most of it is done. We should log separate issues for the remainder of work if necessary, but nothing major seems to block us from running the compiler as a build step any more.
