### ISSUE TITLE
Angular 2 Security Tracking Issue

### ISSUE THREAD

**Issue by mprobst** [angular/angular#8511]
Angular 2 should implement security features on-par with Angular 1. This is a tracking issue for all implementation work.

The basic idea is to implement automatic, secure escaping for all values that can reach the DOM by whitelisting known to be safe patterns, comparable to Angular 1's `$sce` service. By default, with no specific action for developers, Angular apps must be secure. To support all use cases, allow users to explicitly bypass security checks for specific values (`sanitizer.bypassSecurityTrust...`).

This follows the [OWASP recommendations on XSS prevention](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)).

- [x] Basic security infrastructure: `SanitizationService` and safe values (#8387)
- [x] Security Contexts for HTML, Style, Script, URLs, Resource URLs (#8387)
- [x] Sanitize all values before they flow into DOM sinks (#8387)
- [x] Allow marking values as safe for particular (#8387)
- [x] Sanitize Style/CSS values (#8387, #8453)
    - [x] More liberal Style sanitization (#8514)
- [x] Sanitize URL values (#8387, #8453)
    - [x] Allow data: URIs for images and videos (#8661)
- [x] Sanitize HTML values (#8453)
- [x] Log sanitization in development mode (#8522)
- [x] List all unsafe DOM properties (#8479)
- Easy to use safe HTTP interactions
    - [x] Automatically strip XSSI prefixes (#8497)
    - [x] Automatically send back XSRF cookies (#8898)
- Documentation
    - [x] Mention incomplete security implementation in release notes
    - [x] Document breaking changes for security (#8510)
    - [x] Check implementation/API documentation
    - [x] [Security section on Angular site](https://angular.io/docs/ts/latest/guide/security.html)

**Comment by CaptainCodeman** [comment]
This seems to work to disable the sanitizer (i.e. you know all inputs are safe):

```
import { Injectable, provide } from '@angular/core';
import { DomSanitizationService, SecurityContext } from '@angular/platform-browser';

@Injectable()
export class NoSanitizationService {
  sanitize(ctx: SecurityContext, value: any): string {
    return value;
  }
}

export const NO_SANITIZATION_PROVIDERS: any[] = [
  provide(DomSanitizationService, { useClass: NoSanitizationService }),
];
```

Then import and add `NO_SANITIZATION_PROVIDERS` to bootstrap.

**Comment by mprobst** [comment]
@CaptainCodeman yes, that works, but please note that it puts you at very high risk. Experience shows that even extremely good programmers cannot be trusted with judging things like *"you know all inputs are safe"*.

Using this code means your application will have a XSS bug sooner or later.

**Comment by CaptainCodeman** [comment]
> Using this code means your application will have a XSS bug sooner or later.

Sorry, that isn't necessarily true. I agree, you shouldn't do this *without fully knowing and understanding the implications* and the idea of some auto sanitization is a good default for a framework but if you can be certain that the inputs have already been sanitized then there is no issue with treating them as safe. If that wasn't the case then why provide *any* safe options at all?

**Comment by mprobst** [comment]
@CaptainCodeman sure, you might have sanitized inputs now. But they might not be as sanitized as you think, and code changes over time. It's of course your own call, but experience shows that all but hte most trivial applications will gain XSS bugs over time if they don't use auto-escaping.

**Comment by CaptainCodeman** [comment]
Like I said, I think all app security should be approached with full knowledge and awareness of the issues when making decisions that affect it and that would extend to code changes. This is why I prefer to make sure data is sanitized before it is stored and possibly shared as I think if offers better long-term protection than relying on the behavior of whatever the current UI framework happens to be. Of course I applaud anything that any UI framework can do to help provide good default options but I want to be able to turn it off if I decide that is OK.

**Comment by sirdarckcat** [comment]
We need to spend more time on education :(

If some developers still think input validation is a reasonable line of defense, we have definitely failed on the educational front. Perhaps we should invest a lot of time on explaining specific failures that lead to the inherently secure design mantra.

**Comment by CaptainCodeman** [comment]
So are you saying that `sanitizer.bypassSecurityTrust` is unsafe and should be removed?

**Comment by ericmartinezr** [comment]
@mprobst answering to one comment of yours in another issue
>the whitelist implementation is fully secure, by only allowing known to be safe values

The user who reported this issue https://github.com/angular/angular/issues/8491 knew nothing (and I include myself) about this change, and I don't think this is a matter of documentation. What you have there is a *random* behavior for the dom handling. This must not only be documented, but warned by the framework itself. How about a warning like

```
The style [style name] you're trying to bind is not secure , 
refer to this document for alternatives and to see the whitelist [link to some document]
```

I don't need any of this, so using `[style.xxxx]` for some css, and `prop = trustCss('xxx')` (don't remember the exact name) for others is a non-sense. I will have to use @CaptainCodeman 's since now.

**Comment by rjamet** [comment]
> So are you saying that `sanitizer.bypassSecurityTrust` is unsafe and should be removed?

IMO, it's a necessary evil. Angular1 has `$sce.trustAs` which is similar: it's a way to bypass sanitization. It's fine if it causes developers to look at what they do in more detail and in a security-conscious mindset. It's bad if people just perceive it as a way to bypass the $sce:unsafe errors without thinking, because that's an excellent way to cause security bugs.

Also, it has another advantage: it makes dangerous patterns more obvious. I review apps sometime, and for Angular1 it's really simple to just look for trustAs uses, $compile / $parse uses, the $sce functions, and so on. Once you've grepped these, you've covered most of the potential XSS bugs. That's not the case anymore if you kill all sanitization in the app.

**Comment by CaptainCodeman** [comment]
As I already said: you shouldn't do this *without fully knowing and understanding the implications* and the idea of some auto sanitization is a good default for the framework. At no time have I suggested that this should be blindly added to any and all apps without making an informed decision.

But instead of having to explicitly mark every output as safe if that is what I would end up doing, I *may* want to achieve the same thing by using a configuration at an app or component level and it's my choice to do so.

**Comment by rjamet** [comment]
As you say, it's your choice, and I agree with you on that: I'm just trying to explain why I think the work described by that issue is a good default setting, and why the bypassSecurity function is something that's more beneficial than harmful. 

But I'll nit a little more: the goal here isn't to require marking every binding as safe. It's only when doing potentially dangerous things, or things that are sanitizer false positives (unavoidable), that you need the explicit bypass. For now, issue https://github.com/angular/angular/issues/8514 tracks the paranoia of the style sanitizer.

@ericmartinezr makes a good point about the style and HTML sanitization being silent (url prepends unsafe:). Should there be a warning or an info when things get removed ?

**Comment by mprobst** [comment]
@ericmartinezr I concur with @rjamet, could you file a feature request issue for logging failed sanitization attempts, and reference this issue in it? Thanks.

**Comment by xtofian** [comment]
Just noticed that sanitizeUrl returns "unsafe:" + url if validation fails (https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/src/security/url_sanitizer.ts#L41).  

This is probably harmless. However, unsafe: is not a valid scheme, and the URL is appended without any escaping.  There just may be problems in how browsers interpret this.

In other contexts (e.g. closure), we've used the convention to return 'about:invalid#' + explanation (see e.g., http://google.github.io/closure-library/api/source/closure/goog/html/safeurl.js.src.html#l90).

If you wanted to include the URL that failed validation (could be useful for debugging), you could do something like,
'about:invalid#url_failed_sanitization&url=' + encodeURIComponent(url)

**Comment by xtofian** [comment]
To add to the discussion around sanitizer.bypassSecurityTrust:  We've found it to incredibly helpful to use types to represent values that are known to be safe in a particular context.  In cases where the built-in sanitization would reject (or undesirably escape) a value, you can exempt the value from escaping/sanitization by converting it to that type, which essentially "blesses" the value as safe.

The use of types permits you to effectively reason about the correctness of such a "bless as safe". It can be done near the source/origin/construction of the value, rather than near its use (in when it's inserted into a template for instance).   This allows you to reason about overall program safety just based on inspection of the code near the "bless as safe" operation, instead of having to inspect complex data-flows. Essentially, the type contract "transports" the property established based on reasoning about the origin of the value, over to the use of the value (where said property is required).

We've written up some guidelines on structuring the use of  "bless as safe" operations, such as to retain the ability to reason effectively about whole-program correctness, https://github.com/google/safe-html-types/blob/master/doc/safehtml-unchecked.md

For more background, here's a talk and an article:
https://appseccalifornia2016.sched.org/event/4FxM/preventing-security-bugs-through-software-design
http://research.google.com/pubs/archive/42934.pdf

**Comment by mprobst** [comment]
FYI for the folks following along at home, this is now complete implementation wise (modulo bug fixes, and support for XSRF in web workers), but still missing proper documentation, which is work in progress.

**Comment by zoehneto** [comment]
Is there a security reason for removing html5 video elements during sanitization?

**Comment by rjamet** [comment]
zoehneto > I don't see any reason to remove it now, this is probably a leftover from Angular1's sanitizer. I'll look into it around next week.

**Comment by mprobst** [comment]
FYI we now have documentation on security here:
https://angular.io/docs/ts/latest/guide/security.html

I think this concludes this issue. I'm sure we'll have shortcomings and bugs, but let's file separate, more focused issues for those, and close this one. Woohoo.

@zoehneto, could you file a separate issue for the video stuff, so we don't lose track?

**Comment by dborisenkowork** [comment]
SCE is the worst feature of angular

It does nothing since everyone just passing the shit as is.

**Comment by mprobst** [comment]
@dborisenkowork I'm sorry to hear you are having trouble. Is there something specific you're trying to do that doesn't work for you?

**Comment by dborisenkowork** [comment]
@mprobst well sorry for being rude but as I said it just do nothing useful at all and every developer I know just passing values as is and they think about sce as an another boilerplate. I know when my values are safe or not. IMO sce should be disabled by default but still available since it's pretty strong and sometimes useful tool.

**Comment by xtofian** [comment]
@dborisenkowork In our experience, the assumption "I know when my values are safe or not" is simply not true in typical projects.  It might be the case in really small projects (one or two developers, not a lot of code, and the project is short-lived).  For projects that are more complex, it tends to become _very_ difficult to reason about whether or not a value that arrives from somewhere else in the program is really safe for a given context.  Especially if a code base grows over longer periods of time.   XSS vulnerabilities then are pretty much guaranteed.

By-default-safe templating and security type contracts are tools that allow you to structure your software such that you can reason about the absence of XSS vulnerabilities with a reasonable degree of confidence. Some more references linked above, https://github.com/angular/angular/issues/8511#issuecomment-220458051

If you really don't want to use SCE, you can implement and install a "do nothing" SCE.

**Comment by zoechi** [comment]
@dborisenkowork so what do you propose instead?

**Comment by mprobst** [comment]
Just for the record, *passing values as is*, i.e. just binding to the value and have the sanitizer sanitize, is what you're expected to do in most cases, and it'll just work (e.g. when binding into innerHTML).

**Comment by xavierclotet** [comment]
How can I use the no sanitization without the **provide** class provided by @CaptainCodeman

**Comment by mprobst** [comment]
@xavierclotet please consider asking on StackOverflow or gitter, the issues here are not a general support forum.

**Comment by MrCroft** [comment]
old issue, but I've just encountered a weird behavior:
`@HostBinding('style.transform') transform = 'translate3d(100px, 0, 0)';` - **no warning**
`@HostBinding('style.transform') transform = 'scale(1.2)';` - **no warning**
`@HostBinding('style.transform') transform = 'scale(1.2) translate3d(100px, 0, 0)';` - **WARNING: sanitizing unsafe style value scale(1) translate3d(0, 0, 0)**
Why does the last example give the warning, and the first 2 don't?

P.S. Is there no way to do the above binding without getting this warning? And without having to jump through all the "disable the sanitizer" hoops just to bind a plain old css transform? I mean "it's just a css transform! It's not a rocket getting sent to Mars...". I don't know anything about hacking, but how is this a security issue? Could someone really hack you by writing, for example, `window.location.href = "https://github.com";` instead of `scale(1.2)`? And how could someone actually inject that **and** save it in your code that's server-side? I would rather bet that the transformation will simply not work... but I don't think any redirect will be executed if we have `transform(window.location.href = "https://github.com";)`
