### ISSUE TITLE
Tracking: Synchronous Dynamic Component Creation

### ISSUE THREAD

**Issue by tbosch** [angular/angular#9467]
In Angular 2, components can be created programmatically via a ComponentFactory. ComponentFactories are created by the Angular compiler. However, the way to get hold of a ComponentFactory is different between runtime and offline compilation.

[This design doc](https://docs.google.com/document/d/1VRNljdv-6QDY4_I0xx3DHd-IZ19QlthheMLdGGKAAzM/edit#) describes how to unify these differences.

This issue tracks the progress.

- [x] main implementation: See https://github.com/angular/angular/pull/9543
- [x] add `beforeEachProviders` for synchronous tests
- [x] support `CompoentResolverFactory` in router. Also update their docs.
- [ ] deprecate `ComponentResolver` and all lazy loading functionality -> emit warnings
- [ ] docs on angular.io: See https://github.com/angular/angular.io/issues/1745

**Comment by tbosch** [comment]
Decided to not do `beforeEachProviders`. however, it is possible to compile synchronously now.

**Comment by tbosch** [comment]
Copied all remaining TODOs over to https://github.com/angular/angular/issues/9726
