### ISSUE TITLE
Tracking: AppModules

### ISSUE THREAD

**Issue by tbosch** [angular/angular#9726]
AppModules introduce a way to group providers, platform directives/pipes and component factories on a higher level than components.

See [this design doc](https://docs.google.com/document/d/13-LUm1QvOff2631tHz6C4goIHuMzma2_1_PFiLryoIs/edit?usp=sharing) for details.

This issue tracks the progress

- [x] main implementation
- [x] adjust bootstrap to use it
- [x] adjust bootstrap for web workers and server platform to support modules
- [x] create AppModules for web workers and server
- [x] testing support
- [x] define FormsModule and RouterModule
- [x] support for calculating `precompile` based on providers (needed for the router), so called `ANALYZE_FOR_PRECOMPILE`
- [x] deprecate:
  * ComponentResolver and SystemJS based implementations
     * needs (done): router supports `ComponentFactoryResolver`, `precompile` and `ANALYZE_FOR_PRECOMPILE` token`
    * @vsavkin
  * `coreBootstrap` / `coreLoadAndBootstrap`
      * needs (done): converting all platforms to modules)
  * providers arrays in `platform-browser` / `platform-browser-dynamic` / `core/src/application_ref`
      * needs (done): converting all platforms to modules)
  * old way of setting platform pipes / directives
    - needs (done): forms and router have app modules
    - `console.log` in CompilerConfig constructor when non empty pipes / directives are passed in
    - deprecate the symbols for `PLATFORM_DIRECTIVES` / `PLATFORM_PIPES`
is called eagerly.

**Comment by b-strauss** [comment]
Could this be used to bundle css that should only be usable and scoped to components inside an app module? For example, commonly used flex classes.

**Comment by tbosch** [comment]
@b-strauss Sorry, that is not planned yet.

**Comment by b-strauss** [comment]
@tbosch Is that something that would be considered? Should I create an issue for that?

**Comment by tbosch** [comment]
@b-strauss Yes, please.

**Comment by tbosch** [comment]
Support for adding `precompile` components via providers is done here: https://github.com/angular/angular/pull/9874

**Comment by playground** [comment]
@tbosch with the latest build, how can we bootstrap with custom selector?

ComponentResolver is deprecated for dynamic compilation. Use ComponentFactoryResolver together with @AppModule/@Component.precompile or ANALYZE_FOR_PRECOMPILE provider instead.

**Comment by tbosch** [comment]
We don't have a nice API for this yet, sorry.

But you can do the following, please read [this doc (http://g.co/ng/modules)](http://g.co/ng/modules) to understand the concepts before.

```
@NgModule({
  imports: [BrowserModule],
  declarations: [MainComponent],
  entryComponents: [MainComponent]
})
class MainModule {
  constructor(injector: Injector, cfr: ComponentFactoryResolver, appRef: ApplicationRef) {
    const mainCompFactory = cfr.resolveComponentFactory(MainComponent);
    const compRef = mainCompFactory.create(injector, [], 'myCustomSelector');
    appRef.registerChangeDetector(compRef.changeDetectorRef);
  }
}
```

I.e.

1. create a module that lists the component as an `entryComponent`
1. get the `ComponentFactory` from the `ComponentFactoryResolver`
1. create the component
1. register it in `ApplicationRef` via the private API `ApplicationRef.registerChangeDetector` so that the component gets dirty checked

**Comment by tom-mayer** [comment]
@tbosch would it be possible to forward paremeters into the constructor? I only know the elements I want to initialize the component on at runtime (html is fetched via ajax). Probably call something like:
`platformBrowserDynamic().bootstrapModule(MainModule, {selector: 'someSelector'});`
when the html is in the dom and then use the 'selector' parameter in the constructor, as you described.

From what I can see right now boostrapModule does not allow to forward parameters to the module constructor, is that correct? Would you know a way to work around this until there is an API for this?

**Comment by tbosch** [comment]
you can always store data in a top level variable in a module...

**Comment by tom-mayer** [comment]
@tbosch thanks for the pointers, I was trying your approach but I could not call `appRef.registerChangeDetector(compRef.changeDetectorRef);`
Seems the registerChangeDetector method has been removed from ApplicationRef and has been moved into a class called ApplicationRef_. The tc compiler however tells me that the underscore version of the class is not exported by '@angular/core'.

**Comment by tom-mayer** [comment]
@tbosch Out of curiosity, you snippet worked fine in the constructor of the module. However when I put it into ngOnBootstrap of the module, it didn't start the component lifecycle (breakpoint in ngOnInit of the comonent).  I also tried it as a separate method to dynamically attach components to the DOM, are there any additional steps required to start the component?

**Comment by tbosch** [comment]
Not that I know of...

**Comment by tom-mayer** [comment]
Interesting, if I wrap it into a zone.run in ngDoBootstrap it works just fine. A well,... thanks for the great work so far on angular2 !

**Comment by tbosch** [comment]
Could you create a separate issue for this? This is in general just related to module loading, and not to bootstrap of a component with a custom selector.

Your problem is that a service in a root module can not inject a service that is declared in a lazy loaded module, only the other way around. And this makes sense, as loading of modules is intended for code loading, i.e. your root module cannot refer to the service of the lazy loaded module as that code has not been loaded on bootstrap.

**Comment by diestrin** [comment]
Moving, sorry...

**Comment by playground** [comment]
Hi @tbosch ,

Incorporating the following code snippet as you suggested with Angular 2.0.0, the components are getting bootstrapped and lazy loaded, however, they are not getting rendered as if change detection didn't kick in probably due to race condition.  If we explicitly fire changeDetectorRef.detectChanges() in the console, then the components show up.  Is the nice api for this available yet?

public bootstrapWithCustomSelector(moduleFactory: NgModuleFactory<any>,
  selector: string,
  ngClassName: string
): void {
  // Get the parent injector and create the module
  const parentInjector = ReflectiveInjector.resolveAndCreate([], this.appModule.injector);
  const ngModule = moduleFactory.create(parentInjector);

  // Some dependencies from this module
  const appRef = ngModule.injector.get(ApplicationRef);
  const inj = ngModule.injector.get(Injector);
  const lazyLoad = ngModule.injector.get(WuLazyLoadConfig, {component: null});

  if (!lazyLoad.component) {
    throw(`${ngClassName} is not using the WuLazyLoadModule. This is neccesary
      for bootstrap the component. Check the docs.`);
  }

  // Get the component factory and create it
  const compFactory = ngModule.componentFactoryResolver
    .resolveComponentFactory(lazyLoad.component);
  const compRef = compFactory.create(inj, [], selector);

  // Register the change detector to the app and trigger the first detection
  appRef.registerChangeDetector(compRef.changeDetectorRef);
  compRef.changeDetectorRef.detectChanges();
}
